package market

import (
	"context"
	"log/slog"

	"github.com/exploded/game/internal/db"
)

// SeedStocks inserts all ASX 200 and S&P 500 constituents into the stocks table.
// Uses INSERT OR IGNORE so it's safe to call on every startup.
func SeedStocks(ctx context.Context, q *db.Queries) {
	count := 0
	for _, s := range ASX200 {
		q.InsertStock(ctx, db.InsertStockParams{
			Symbol:   s.Symbol,
			Name:     s.Name,
			Market:   "asx",
			Sector:   s.Sector,
			Currency: "AUD",
		})
		count++
	}
	for _, s := range SP500 {
		q.InsertStock(ctx, db.InsertStockParams{
			Symbol:   s.Symbol,
			Name:     s.Name,
			Market:   "sp500",
			Sector:   s.Sector,
			Currency: "USD",
		})
		count++
	}
	slog.Info("stocks seeded", "total", count)
}

type StockInfo struct {
	Symbol string
	Name   string
	Sector string
}

// ASX200 contains the top ASX 200 constituents.
// Full list can be expanded over time.
var ASX200 = []StockInfo{
	{"BHP", "BHP Group", "Materials"},
	{"CBA", "Commonwealth Bank", "Financials"},
	{"CSL", "CSL Limited", "Healthcare"},
	{"NAB", "National Australia Bank", "Financials"},
	{"WBC", "Westpac Banking", "Financials"},
	{"ANZ", "ANZ Group", "Financials"},
	{"WES", "Wesfarmers", "Consumer Discretionary"},
	{"MQG", "Macquarie Group", "Financials"},
	{"FMG", "Fortescue", "Materials"},
	{"WOW", "Woolworths Group", "Consumer Staples"},
	{"TLS", "Telstra Group", "Communication Services"},
	{"RIO", "Rio Tinto", "Materials"},
	{"ALL", "Aristocrat Leisure", "Consumer Discretionary"},
	{"WDS", "Woodside Energy", "Energy"},
	{"COL", "Coles Group", "Consumer Staples"},
	{"STO", "Santos", "Energy"},
	{"TCL", "Transurban Group", "Industrials"},
	{"GMG", "Goodman Group", "Real Estate"},
	{"REA", "REA Group", "Communication Services"},
	{"QBE", "QBE Insurance", "Financials"},
	{"SUN", "Suncorp Group", "Financials"},
	{"IAG", "Insurance Australia", "Financials"},
	{"ORG", "Origin Energy", "Energy"},
	{"SOL", "WH Soul Pattinson", "Financials"},
	{"NCM", "Newcrest Mining", "Materials"},
	{"MIN", "Mineral Resources", "Materials"},
	{"S32", "South32", "Materials"},
	{"JHX", "James Hardie", "Materials"},
	{"AMC", "Amcor", "Materials"},
	{"SHL", "Sonic Healthcare", "Healthcare"},
	{"RHC", "Ramsay Health Care", "Healthcare"},
	{"CPU", "Computershare", "Information Technology"},
	{"APA", "APA Group", "Utilities"},
	{"XRO", "Xero", "Information Technology"},
	{"CAR", "CAR Group", "Communication Services"},
	{"TWE", "Treasury Wine Estates", "Consumer Staples"},
	{"AGL", "AGL Energy", "Utilities"},
	{"SEK", "Seek", "Communication Services"},
	{"BSL", "BlueScope Steel", "Materials"},
	{"DXS", "Dexus", "Real Estate"},
	{"MGR", "Mirvac Group", "Real Estate"},
	{"GPT", "GPT Group", "Real Estate"},
	{"SGP", "Stockland", "Real Estate"},
	{"VCX", "Vicinity Centres", "Real Estate"},
	{"SCG", "Scentre Group", "Real Estate"},
	{"ALD", "Ampol", "Energy"},
	{"LLC", "Lendlease", "Real Estate"},
	{"ORA", "Orora", "Materials"},
	{"ILU", "Iluka Resources", "Materials"},
	{"EVN", "Evolution Mining", "Materials"},
	{"NST", "Northern Star", "Materials"},
	{"GNC", "GrainCorp", "Consumer Staples"},
	{"ALX", "Atlas Arteria", "Industrials"},
	{"CWY", "Cleanaway Waste", "Industrials"},
	{"AZJ", "Aurizon", "Industrials"},
	{"QAN", "Qantas Airways", "Industrials"},
	{"TAH", "Tabcorp", "Consumer Discretionary"},
	{"IGO", "IGO", "Materials"},
	{"LYC", "Lynas Rare Earths", "Materials"},
	{"PLS", "Pilbara Minerals", "Materials"},
	{"BEN", "Bendigo Bank", "Financials"},
	{"BOQ", "Bank of Queensland", "Financials"},
	{"MPL", "Medibank Private", "Financials"},
	{"NHF", "NIB Holdings", "Financials"},
	{"PDN", "Paladin Energy", "Energy"},
	{"WHC", "Whitehaven Coal", "Energy"},
	{"29M", "29Metals", "Materials"},
	{"ASX", "ASX Limited", "Financials"},
	{"CEN", "Contact Energy", "Utilities"},
	{"CHC", "Charter Hall", "Real Estate"},
	{"COH", "Cochlear", "Healthcare"},
	{"CTD", "Corporate Travel", "Consumer Discretionary"},
	{"DEG", "De Grey Mining", "Materials"},
	{"DRR", "Deterra Royalties", "Materials"},
	{"EDV", "Endeavour Group", "Consumer Staples"},
	{"ELD", "Elders", "Consumer Staples"},
	{"FPH", "Fisher & Paykel", "Healthcare"},
	{"HVN", "Harvey Norman", "Consumer Discretionary"},
	{"IEL", "IDP Education", "Consumer Discretionary"},
	{"JBH", "JB Hi-Fi", "Consumer Discretionary"},
	{"LNW", "Light & Wonder", "Consumer Discretionary"},
	{"LOV", "Lovisa Holdings", "Consumer Discretionary"},
	{"LTR", "Liontown Resources", "Materials"},
	{"MEZ", "Meridian Energy", "Utilities"},
	{"NEC", "Nine Entertainment", "Communication Services"},
	{"NEM", "Newmont", "Materials"},
	{"NXT", "NextDC", "Information Technology"},
	{"ORI", "Orica", "Materials"},
	{"PME", "Pro Medicus", "Healthcare"},
	{"PMV", "Premier Investments", "Consumer Discretionary"},
	{"QUB", "Qube Holdings", "Industrials"},
	{"REH", "Reece", "Industrials"},
	{"RMD", "ResMed", "Healthcare"},
	{"SGM", "Sims", "Materials"},
	{"SFR", "Sandfire Resources", "Materials"},
	{"SPK", "Spark New Zealand", "Communication Services"},
	{"STX", "Strike Energy", "Energy"},
	{"SUL", "Super Retail Group", "Consumer Discretionary"},
	{"SVW", "Seven Group", "Industrials"},
	{"SYA", "Sayona Mining", "Materials"},
	{"TLC", "Lottery Corp", "Consumer Discretionary"},
	{"TPG", "TPG Telecom", "Communication Services"},
	{"VEA", "Viva Energy", "Energy"},
	{"WEB", "Webjet", "Consumer Discretionary"},
	{"WOR", "Worley", "Energy"},
	{"WTC", "WiseTech Global", "Information Technology"},
}

// SP500 contains the top S&P 500 constituents.
var SP500 = []StockInfo{
	{"AAPL", "Apple Inc.", "Information Technology"},
	{"MSFT", "Microsoft Corp.", "Information Technology"},
	{"AMZN", "Amazon.com Inc.", "Consumer Discretionary"},
	{"NVDA", "NVIDIA Corp.", "Information Technology"},
	{"GOOGL", "Alphabet Inc. A", "Communication Services"},
	{"META", "Meta Platforms", "Communication Services"},
	{"BRK.B", "Berkshire Hathaway B", "Financials"},
	{"TSLA", "Tesla Inc.", "Consumer Discretionary"},
	{"UNH", "UnitedHealth Group", "Healthcare"},
	{"LLY", "Eli Lilly", "Healthcare"},
	{"JPM", "JPMorgan Chase", "Financials"},
	{"V", "Visa Inc.", "Financials"},
	{"XOM", "Exxon Mobil", "Energy"},
	{"JNJ", "Johnson & Johnson", "Healthcare"},
	{"MA", "Mastercard", "Financials"},
	{"PG", "Procter & Gamble", "Consumer Staples"},
	{"AVGO", "Broadcom Inc.", "Information Technology"},
	{"HD", "Home Depot", "Consumer Discretionary"},
	{"COST", "Costco Wholesale", "Consumer Staples"},
	{"MRK", "Merck & Co.", "Healthcare"},
	{"ABBV", "AbbVie Inc.", "Healthcare"},
	{"CVX", "Chevron Corp.", "Energy"},
	{"CRM", "Salesforce Inc.", "Information Technology"},
	{"KO", "Coca-Cola Co.", "Consumer Staples"},
	{"PEP", "PepsiCo Inc.", "Consumer Staples"},
	{"ADBE", "Adobe Inc.", "Information Technology"},
	{"WMT", "Walmart Inc.", "Consumer Staples"},
	{"BAC", "Bank of America", "Financials"},
	{"MCD", "McDonald's Corp.", "Consumer Discretionary"},
	{"TMO", "Thermo Fisher", "Healthcare"},
	{"CSCO", "Cisco Systems", "Information Technology"},
	{"ACN", "Accenture", "Information Technology"},
	{"ABT", "Abbott Labs", "Healthcare"},
	{"NFLX", "Netflix Inc.", "Communication Services"},
	{"LIN", "Linde plc", "Materials"},
	{"DHR", "Danaher Corp.", "Healthcare"},
	{"AMD", "Advanced Micro Devices", "Information Technology"},
	{"TXN", "Texas Instruments", "Information Technology"},
	{"WFC", "Wells Fargo", "Financials"},
	{"PM", "Philip Morris", "Consumer Staples"},
	{"ORCL", "Oracle Corp.", "Information Technology"},
	{"CMCSA", "Comcast Corp.", "Communication Services"},
	{"COP", "ConocoPhillips", "Energy"},
	{"INTC", "Intel Corp.", "Information Technology"},
	{"VZ", "Verizon Communications", "Communication Services"},
	{"IBM", "IBM Corp.", "Information Technology"},
	{"INTU", "Intuit Inc.", "Information Technology"},
	{"AMGN", "Amgen Inc.", "Healthcare"},
	{"DIS", "Walt Disney Co.", "Communication Services"},
	{"QCOM", "Qualcomm Inc.", "Information Technology"},
	{"CAT", "Caterpillar Inc.", "Industrials"},
	{"NOW", "ServiceNow Inc.", "Information Technology"},
	{"GE", "GE Aerospace", "Industrials"},
	{"SPGI", "S&P Global", "Financials"},
	{"ISRG", "Intuitive Surgical", "Healthcare"},
	{"PFE", "Pfizer Inc.", "Healthcare"},
	{"AXP", "American Express", "Financials"},
	{"RTX", "RTX Corp.", "Industrials"},
	{"GS", "Goldman Sachs", "Financials"},
	{"T", "AT&T Inc.", "Communication Services"},
	{"BLK", "BlackRock Inc.", "Financials"},
	{"LOW", "Lowe's Cos.", "Consumer Discretionary"},
	{"BKNG", "Booking Holdings", "Consumer Discretionary"},
	{"UNP", "Union Pacific", "Industrials"},
	{"ELV", "Elevance Health", "Healthcare"},
	{"DE", "Deere & Co.", "Industrials"},
	{"MDT", "Medtronic plc", "Healthcare"},
	{"AMAT", "Applied Materials", "Information Technology"},
	{"SYK", "Stryker Corp.", "Healthcare"},
	{"SCHW", "Charles Schwab", "Financials"},
	{"ADP", "ADP Inc.", "Industrials"},
	{"GILD", "Gilead Sciences", "Healthcare"},
	{"MDLZ", "Mondelez Intl.", "Consumer Staples"},
	{"MMC", "Marsh McLennan", "Financials"},
	{"VRTX", "Vertex Pharma", "Healthcare"},
	{"TJX", "TJX Companies", "Consumer Discretionary"},
	{"CB", "Chubb Limited", "Financials"},
	{"PGR", "Progressive Corp.", "Financials"},
	{"CI", "Cigna Group", "Healthcare"},
	{"TMUS", "T-Mobile US", "Communication Services"},
	{"LRCX", "Lam Research", "Information Technology"},
	{"ETN", "Eaton Corp.", "Industrials"},
	{"BSX", "Boston Scientific", "Healthcare"},
	{"ZTS", "Zoetis Inc.", "Healthcare"},
	{"MU", "Micron Technology", "Information Technology"},
	{"PANW", "Palo Alto Networks", "Information Technology"},
	{"REGN", "Regeneron Pharma", "Healthcare"},
	{"FI", "Fiserv Inc.", "Financials"},
	{"SNPS", "Synopsys Inc.", "Information Technology"},
	{"KLAC", "KLA Corp.", "Information Technology"},
	{"SO", "Southern Co.", "Utilities"},
	{"DUK", "Duke Energy", "Utilities"},
	{"SLB", "Schlumberger", "Energy"},
	{"ICE", "Intercontinental Exchange", "Financials"},
	{"EOG", "EOG Resources", "Energy"},
	{"CME", "CME Group", "Financials"},
	{"CL", "Colgate-Palmolive", "Consumer Staples"},
	{"HUM", "Humana Inc.", "Healthcare"},
	{"NOC", "Northrop Grumman", "Industrials"},
	{"APD", "Air Products", "Materials"},
	{"MO", "Altria Group", "Consumer Staples"},
	{"PYPL", "PayPal Holdings", "Financials"},
	{"USB", "U.S. Bancorp", "Financials"},
	{"PNC", "PNC Financial", "Financials"},
	{"AON", "Aon plc", "Financials"},
	{"ITW", "Illinois Tool Works", "Industrials"},
	{"SHW", "Sherwin-Williams", "Materials"},
	{"EMR", "Emerson Electric", "Industrials"},
	{"CDNS", "Cadence Design", "Information Technology"},
	{"GD", "General Dynamics", "Industrials"},
	{"TGT", "Target Corp.", "Consumer Discretionary"},
	{"MCO", "Moody's Corp.", "Financials"},
	{"HCA", "HCA Healthcare", "Healthcare"},
	{"MSI", "Motorola Solutions", "Information Technology"},
	{"ABNB", "Airbnb Inc.", "Consumer Discretionary"},
	{"UBER", "Uber Technologies", "Industrials"},
	{"COIN", "Coinbase Global", "Financials"},
	{"SNOW", "Snowflake Inc.", "Information Technology"},
	{"CRWD", "CrowdStrike", "Information Technology"},
	{"DDOG", "Datadog Inc.", "Information Technology"},
	{"NET", "Cloudflare Inc.", "Information Technology"},
	{"SHOP", "Shopify Inc.", "Information Technology"},
	{"SQ", "Block Inc.", "Financials"},
	{"PLTR", "Palantir Technologies", "Information Technology"},
	{"RIVN", "Rivian Automotive", "Consumer Discretionary"},
	{"LCID", "Lucid Group", "Consumer Discretionary"},
	{"NKE", "Nike Inc.", "Consumer Discretionary"},
	{"SBUX", "Starbucks Corp.", "Consumer Discretionary"},
	{"BA", "Boeing Co.", "Industrials"},
	{"LMT", "Lockheed Martin", "Industrials"},
	{"FDX", "FedEx Corp.", "Industrials"},
	{"UPS", "United Parcel Service", "Industrials"},
	{"GM", "General Motors", "Consumer Discretionary"},
	{"F", "Ford Motor Co.", "Consumer Discretionary"},
	{"DAL", "Delta Air Lines", "Industrials"},
	{"AAL", "American Airlines", "Industrials"},
	{"MAR", "Marriott Intl.", "Consumer Discretionary"},
	{"HLT", "Hilton Worldwide", "Consumer Discretionary"},
	{"WDAY", "Workday Inc.", "Information Technology"},
	{"ZM", "Zoom Video", "Information Technology"},
	{"ROKU", "Roku Inc.", "Communication Services"},
	{"SPOT", "Spotify Technology", "Communication Services"},
	{"SNAP", "Snap Inc.", "Communication Services"},
	{"PINS", "Pinterest Inc.", "Communication Services"},
	{"DOCU", "DocuSign Inc.", "Information Technology"},
	{"BILL", "BILL Holdings", "Information Technology"},
	{"TTD", "Trade Desk Inc.", "Information Technology"},
	{"MRVL", "Marvell Technology", "Information Technology"},
	{"ON", "ON Semiconductor", "Information Technology"},
	{"ENPH", "Enphase Energy", "Information Technology"},
	{"SEDG", "SolarEdge Technologies", "Information Technology"},
	{"FSLR", "First Solar Inc.", "Information Technology"},
	{"NEE", "NextEra Energy", "Utilities"},
	{"AEP", "American Electric Power", "Utilities"},
	{"D", "Dominion Energy", "Utilities"},
	{"EXC", "Exelon Corp.", "Utilities"},
	{"XEL", "Xcel Energy", "Utilities"},
	{"WM", "Waste Management", "Industrials"},
	{"RSG", "Republic Services", "Industrials"},
}
