// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
)

type Achievement struct {
	ID          int64
	Key         string
	Name        string
	Description string
	Icon        string
}

type ActivityFeed struct {
	ID        int64
	GameID    int64
	UserID    int64
	Action    string
	Detail    string
	IsPublic  int64
	CreatedAt string
}

type Avatar struct {
	ID             int64
	Key            string
	Name           string
	ImagePath      string
	Category       string
	AchievementKey sql.NullString
	SortOrder      int64
}

type ContactMessage struct {
	ID        int64
	UserID    sql.NullInt64
	Name      string
	Email     string
	Message   string
	IsRead    int64
	CreatedAt string
}

type ExchangeRate struct {
	ID         int64
	Date       string
	RateAudUsd int64
	CreatedAt  string
}

type Game struct {
	ID                   int64
	CreatedBy            int64
	Name                 string
	Description          string
	Status               string
	Markets              string
	StartingBalance      int64
	BaseCurrency         string
	MaxParticipants      sql.NullInt64
	StartDate            string
	EndDate              string
	AllowShort           int64
	TradeFee             int64
	ReferralBonusPct     int64
	RecurringInterval    sql.NullString
	ParentGameID         sql.NullInt64
	TemplateID           sql.NullInt64
	IsPublic             int64
	PortfolioVisibility  string
	CreditInterestRate   int64
	LeverageInterestRate int64
	MinStockPrice        sql.NullInt64
	MaxStockPrice        sql.NullInt64
	MarginTrading        int64
	LimitOrders          int64
	StopLoss             int64
	FractionalShares     int64
	CreatedAt            string
	UpdatedAt            string
}

type GameInvite struct {
	ID        int64
	GameID    int64
	Code      string
	CreatedBy int64
	MaxUses   sql.NullInt64
	UseCount  int64
	ExpiresAt sql.NullString
	CreatedAt string
}

type GameMessage struct {
	ID        int64
	GameID    int64
	UserID    int64
	Message   string
	CreatedAt string
}

type GameStartingStock struct {
	ID       int64
	GameID   int64
	StockID  int64
	Quantity int64
}

type GameTemplate struct {
	ID              int64
	Name            string
	Description     string
	Markets         string
	StartingBalance int64
	BaseCurrency    string
	DurationDays    int64
	AllowShort      int64
	TradeFee        int64
	IsBuiltin       int64
	CreatedBy       sql.NullInt64
	CreatedAt       string
}

type Holding struct {
	ID            int64
	ParticipantID int64
	StockID       int64
	Quantity      int64
	AvgCost       int64
	CurrentValue  int64
	UpdatedAt     string
}

type LimitOrder struct {
	ID            int64
	ParticipantID int64
	StockID       int64
	Type          string
	Quantity      int64
	LimitPrice    int64
	Status        string
	CreatedAt     string
	ExpiresAt     sql.NullString
	FilledAt      sql.NullString
}

type LobbyMessage struct {
	ID        int64
	UserID    int64
	Message   string
	CreatedAt string
}

type Notification struct {
	ID        int64
	UserID    int64
	GameID    sql.NullInt64
	Type      string
	Title     string
	Message   string
	IsRead    int64
	CreatedAt string
}

type Participant struct {
	ID             int64
	GameID         int64
	UserID         int64
	CashBalance    int64
	PortfolioValue int64
	IsPublic       int64
	JoinedAt       string
}

type PortfolioSnapshot struct {
	ID            int64
	ParticipantID int64
	Date          string
	CashBalance   int64
	HoldingsValue int64
	TotalValue    int64
}

type PriceFetchLog struct {
	ID            int64
	Market        string
	Status        string
	StocksUpdated int64
	ErrorMsg      sql.NullString
	DurationMs    sql.NullInt64
	CreatedAt     string
}

type ReferralBonuse struct {
	ID          int64
	InviteID    int64
	ReferrerID  int64
	ReferredID  int64
	GameID      int64
	BonusAmount int64
	CreatedAt   string
}

type Session struct {
	ID        string
	UserID    int64
	ExpiresAt string
	CreatedAt string
}

type Stock struct {
	ID        int64
	Symbol    string
	Name      string
	Market    string
	Sector    string
	Currency  string
	IsActive  int64
	CreatedAt string
}

type StockPrice struct {
	ID        int64
	StockID   int64
	Date      string
	Open      int64
	High      int64
	Low       int64
	Close     int64
	Volume    int64
	CreatedAt string
}

type Transaction struct {
	ID               int64
	ParticipantID    int64
	StockID          int64
	Type             string
	Quantity         int64
	Price            int64
	Total            int64
	ConvertedTotal   int64
	ExchangeRateUsed int64
	Fee              int64
	CreatedAt        string
}

type User struct {
	ID         int64
	GoogleID   string
	Email      string
	Name       string
	PictureUrl sql.NullString
	IsAdmin    int64
	AvatarID   sql.NullInt64
	CreatedAt  string
	LastLogin  string
	DeletedAt  sql.NullString
}

type UserAchievement struct {
	ID            int64
	UserID        int64
	AchievementID int64
	GameID        sql.NullInt64
	EarnedAt      string
}

type Watchlist struct {
	ID            int64
	ParticipantID int64
	StockID       int64
	CreatedAt     string
}
