// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"
	"database/sql"
)

const addStartingStock = `-- name: AddStartingStock :exec

INSERT OR REPLACE INTO game_starting_stocks (game_id, stock_id, quantity)
VALUES (?, ?, ?)
`

type AddStartingStockParams struct {
	GameID   int64
	StockID  int64
	Quantity int64
}

// =============================================================================
// Starting Portfolio (Feature 18)
// =============================================================================
func (q *Queries) AddStartingStock(ctx context.Context, arg AddStartingStockParams) error {
	_, err := q.db.ExecContext(ctx, addStartingStock, arg.GameID, arg.StockID, arg.Quantity)
	return err
}

const addToWatchlist = `-- name: AddToWatchlist :exec

INSERT OR IGNORE INTO watchlist (participant_id, stock_id) VALUES (?, ?)
`

type AddToWatchlistParams struct {
	ParticipantID int64
	StockID       int64
}

// =============================================================================
// Watchlist (Feature 2)
// =============================================================================
func (q *Queries) AddToWatchlist(ctx context.Context, arg AddToWatchlistParams) error {
	_, err := q.db.ExecContext(ctx, addToWatchlist, arg.ParticipantID, arg.StockID)
	return err
}

const advancePendingGames = `-- name: AdvancePendingGames :exec
UPDATE games SET status = 'active', updated_at = datetime('now')
WHERE status = 'pending' AND start_date <= ?
`

func (q *Queries) AdvancePendingGames(ctx context.Context, startDate string) error {
	_, err := q.db.ExecContext(ctx, advancePendingGames, startDate)
	return err
}

const cancelLimitOrder = `-- name: CancelLimitOrder :exec
UPDATE limit_orders SET status = 'cancelled' WHERE id = ?
`

func (q *Queries) CancelLimitOrder(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, cancelLimitOrder, id)
	return err
}

const clearUserAvatar = `-- name: ClearUserAvatar :exec
UPDATE users SET avatar_id = NULL WHERE id = ?
`

func (q *Queries) ClearUserAvatar(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, clearUserAvatar, id)
	return err
}

const countContactMessages = `-- name: CountContactMessages :one
SELECT COUNT(*) FROM contact_messages
`

func (q *Queries) CountContactMessages(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countContactMessages)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countFinishedGames = `-- name: CountFinishedGames :one
SELECT COUNT(*) FROM games WHERE status IN ('finished', 'cancelled')
`

func (q *Queries) CountFinishedGames(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countFinishedGames)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countLobbyMessages = `-- name: CountLobbyMessages :one
SELECT COUNT(*) FROM lobby_messages
`

func (q *Queries) CountLobbyMessages(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countLobbyMessages)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countMessages = `-- name: CountMessages :one
SELECT COUNT(*) FROM game_messages WHERE game_id = ?
`

func (q *Queries) CountMessages(ctx context.Context, gameID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countMessages, gameID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countOpenOrders = `-- name: CountOpenOrders :one
SELECT COUNT(*) FROM limit_orders WHERE participant_id = ? AND status = 'open'
`

func (q *Queries) CountOpenOrders(ctx context.Context, participantID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countOpenOrders, participantID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countParticipants = `-- name: CountParticipants :one
SELECT COUNT(*) FROM participants WHERE game_id = ?
`

func (q *Queries) CountParticipants(ctx context.Context, gameID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countParticipants, gameID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countReferralBonuses = `-- name: CountReferralBonuses :one
SELECT COUNT(*) FROM referral_bonuses WHERE referrer_id = ? AND game_id = ?
`

type CountReferralBonusesParams struct {
	ReferrerID int64
	GameID     int64
}

func (q *Queries) CountReferralBonuses(ctx context.Context, arg CountReferralBonusesParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countReferralBonuses, arg.ReferrerID, arg.GameID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countStocks = `-- name: CountStocks :one
SELECT COUNT(*) FROM stocks WHERE is_active = 1
`

func (q *Queries) CountStocks(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countStocks)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countStocksMissingPrices = `-- name: CountStocksMissingPrices :one

SELECT COUNT(*) FROM stocks s
WHERE s.is_active = 1
AND s.id NOT IN (
    SELECT sp.stock_id FROM stock_prices sp WHERE sp.date = ?1
)
`

// =============================================================================
// Admin - Price Health (Feature 21)
// =============================================================================
func (q *Queries) CountStocksMissingPrices(ctx context.Context, targetDate string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countStocksMissingPrices, targetDate)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTransactions = `-- name: CountTransactions :one
SELECT COUNT(*) FROM transactions WHERE participant_id = ?
`

func (q *Queries) CountTransactions(ctx context.Context, participantID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countTransactions, participantID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUnreadContactMessages = `-- name: CountUnreadContactMessages :one
SELECT COUNT(*) FROM contact_messages WHERE is_read = 0
`

func (q *Queries) CountUnreadContactMessages(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUnreadContactMessages)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUnreadNotifications = `-- name: CountUnreadNotifications :one
SELECT COUNT(*) FROM notifications WHERE user_id = ? AND is_read = 0
`

func (q *Queries) CountUnreadNotifications(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUnreadNotifications, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createContactMessage = `-- name: CreateContactMessage :exec

INSERT INTO contact_messages (user_id, name, email, message)
VALUES (?, ?, ?, ?)
`

type CreateContactMessageParams struct {
	UserID  sql.NullInt64
	Name    string
	Email   string
	Message string
}

// =============================================================================
// Contact Messages
// =============================================================================
func (q *Queries) CreateContactMessage(ctx context.Context, arg CreateContactMessageParams) error {
	_, err := q.db.ExecContext(ctx, createContactMessage,
		arg.UserID,
		arg.Name,
		arg.Email,
		arg.Message,
	)
	return err
}

const createGame = `-- name: CreateGame :one

INSERT INTO games (created_by, name, description, markets, starting_balance, base_currency, max_participants, start_date, end_date, allow_short, trade_fee, recurring_interval, referral_bonus_pct)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, created_by, name, description, status, markets, starting_balance, base_currency, max_participants, start_date, end_date, allow_short, trade_fee, referral_bonus_pct, recurring_interval, parent_game_id, template_id, created_at, updated_at
`

type CreateGameParams struct {
	CreatedBy         int64
	Name              string
	Description       string
	Markets           string
	StartingBalance   int64
	BaseCurrency      string
	MaxParticipants   sql.NullInt64
	StartDate         string
	EndDate           string
	AllowShort        int64
	TradeFee          int64
	RecurringInterval sql.NullString
	ReferralBonusPct  int64
}

// =============================================================================
// Games
// =============================================================================
func (q *Queries) CreateGame(ctx context.Context, arg CreateGameParams) (Game, error) {
	row := q.db.QueryRowContext(ctx, createGame,
		arg.CreatedBy,
		arg.Name,
		arg.Description,
		arg.Markets,
		arg.StartingBalance,
		arg.BaseCurrency,
		arg.MaxParticipants,
		arg.StartDate,
		arg.EndDate,
		arg.AllowShort,
		arg.TradeFee,
		arg.RecurringInterval,
		arg.ReferralBonusPct,
	)
	var i Game
	err := row.Scan(
		&i.ID,
		&i.CreatedBy,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.Markets,
		&i.StartingBalance,
		&i.BaseCurrency,
		&i.MaxParticipants,
		&i.StartDate,
		&i.EndDate,
		&i.AllowShort,
		&i.TradeFee,
		&i.ReferralBonusPct,
		&i.RecurringInterval,
		&i.ParentGameID,
		&i.TemplateID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createGameTemplate = `-- name: CreateGameTemplate :one

INSERT INTO game_templates (name, description, markets, starting_balance, base_currency, duration_days, allow_short, trade_fee, is_builtin, created_by)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, name, description, markets, starting_balance, base_currency, duration_days, allow_short, trade_fee, is_builtin, created_by, created_at
`

type CreateGameTemplateParams struct {
	Name            string
	Description     string
	Markets         string
	StartingBalance int64
	BaseCurrency    string
	DurationDays    int64
	AllowShort      int64
	TradeFee        int64
	IsBuiltin       int64
	CreatedBy       sql.NullInt64
}

// =============================================================================
// Game Templates (Feature 16)
// =============================================================================
func (q *Queries) CreateGameTemplate(ctx context.Context, arg CreateGameTemplateParams) (GameTemplate, error) {
	row := q.db.QueryRowContext(ctx, createGameTemplate,
		arg.Name,
		arg.Description,
		arg.Markets,
		arg.StartingBalance,
		arg.BaseCurrency,
		arg.DurationDays,
		arg.AllowShort,
		arg.TradeFee,
		arg.IsBuiltin,
		arg.CreatedBy,
	)
	var i GameTemplate
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Markets,
		&i.StartingBalance,
		&i.BaseCurrency,
		&i.DurationDays,
		&i.AllowShort,
		&i.TradeFee,
		&i.IsBuiltin,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const createInvite = `-- name: CreateInvite :one

INSERT INTO game_invites (game_id, code, created_by, max_uses, expires_at)
VALUES (?, ?, ?, ?, ?)
RETURNING id, game_id, code, created_by, max_uses, use_count, expires_at, created_at
`

type CreateInviteParams struct {
	GameID    int64
	Code      string
	CreatedBy int64
	MaxUses   sql.NullInt64
	ExpiresAt sql.NullString
}

// =============================================================================
// Invite Links (Feature 6)
// =============================================================================
func (q *Queries) CreateInvite(ctx context.Context, arg CreateInviteParams) (GameInvite, error) {
	row := q.db.QueryRowContext(ctx, createInvite,
		arg.GameID,
		arg.Code,
		arg.CreatedBy,
		arg.MaxUses,
		arg.ExpiresAt,
	)
	var i GameInvite
	err := row.Scan(
		&i.ID,
		&i.GameID,
		&i.Code,
		&i.CreatedBy,
		&i.MaxUses,
		&i.UseCount,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const createLimitOrder = `-- name: CreateLimitOrder :one

INSERT INTO limit_orders (participant_id, stock_id, type, quantity, limit_price, expires_at)
VALUES (?, ?, ?, ?, ?, ?)
RETURNING id, participant_id, stock_id, type, quantity, limit_price, status, created_at, expires_at, filled_at
`

type CreateLimitOrderParams struct {
	ParticipantID int64
	StockID       int64
	Type          string
	Quantity      int64
	LimitPrice    int64
	ExpiresAt     sql.NullString
}

// =============================================================================
// Limit Orders (Feature 1)
// =============================================================================
func (q *Queries) CreateLimitOrder(ctx context.Context, arg CreateLimitOrderParams) (LimitOrder, error) {
	row := q.db.QueryRowContext(ctx, createLimitOrder,
		arg.ParticipantID,
		arg.StockID,
		arg.Type,
		arg.Quantity,
		arg.LimitPrice,
		arg.ExpiresAt,
	)
	var i LimitOrder
	err := row.Scan(
		&i.ID,
		&i.ParticipantID,
		&i.StockID,
		&i.Type,
		&i.Quantity,
		&i.LimitPrice,
		&i.Status,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.FilledAt,
	)
	return i, err
}

const createLobbyMessage = `-- name: CreateLobbyMessage :one

INSERT INTO lobby_messages (user_id, message)
VALUES (?, ?)
RETURNING id, user_id, message, created_at
`

type CreateLobbyMessageParams struct {
	UserID  int64
	Message string
}

// =============================================================================
// Lobby Chat
// =============================================================================
func (q *Queries) CreateLobbyMessage(ctx context.Context, arg CreateLobbyMessageParams) (LobbyMessage, error) {
	row := q.db.QueryRowContext(ctx, createLobbyMessage, arg.UserID, arg.Message)
	var i LobbyMessage
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Message,
		&i.CreatedAt,
	)
	return i, err
}

const createMessage = `-- name: CreateMessage :one

INSERT INTO game_messages (game_id, user_id, message)
VALUES (?, ?, ?)
RETURNING id, game_id, user_id, message, created_at
`

type CreateMessageParams struct {
	GameID  int64
	UserID  int64
	Message string
}

// =============================================================================
// Game Chat (Feature 7)
// =============================================================================
func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (GameMessage, error) {
	row := q.db.QueryRowContext(ctx, createMessage, arg.GameID, arg.UserID, arg.Message)
	var i GameMessage
	err := row.Scan(
		&i.ID,
		&i.GameID,
		&i.UserID,
		&i.Message,
		&i.CreatedAt,
	)
	return i, err
}

const createNotification = `-- name: CreateNotification :exec

INSERT INTO notifications (user_id, game_id, type, title, message)
VALUES (?, ?, ?, ?, ?)
`

type CreateNotificationParams struct {
	UserID  int64
	GameID  sql.NullInt64
	Type    string
	Title   string
	Message string
}

// =============================================================================
// Notifications (Feature 19)
// =============================================================================
func (q *Queries) CreateNotification(ctx context.Context, arg CreateNotificationParams) error {
	_, err := q.db.ExecContext(ctx, createNotification,
		arg.UserID,
		arg.GameID,
		arg.Type,
		arg.Title,
		arg.Message,
	)
	return err
}

const createSession = `-- name: CreateSession :one

INSERT INTO sessions (id, user_id, expires_at)
VALUES (?, ?, ?)
RETURNING id, user_id, expires_at, created_at
`

type CreateSessionParams struct {
	ID        string
	UserID    int64
	ExpiresAt string
}

// =============================================================================
// Sessions
// =============================================================================
func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRowContext(ctx, createSession, arg.ID, arg.UserID, arg.ExpiresAt)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :exec
DELETE FROM sessions WHERE expires_at <= datetime('now')
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredSessions)
	return err
}

const deleteGameTemplate = `-- name: DeleteGameTemplate :exec
DELETE FROM game_templates WHERE id = ? AND is_builtin = 0
`

func (q *Queries) DeleteGameTemplate(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteGameTemplate, id)
	return err
}

const deleteHolding = `-- name: DeleteHolding :exec
DELETE FROM holdings WHERE participant_id = ? AND stock_id = ?
`

type DeleteHoldingParams struct {
	ParticipantID int64
	StockID       int64
}

func (q *Queries) DeleteHolding(ctx context.Context, arg DeleteHoldingParams) error {
	_, err := q.db.ExecContext(ctx, deleteHolding, arg.ParticipantID, arg.StockID)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE id = ?
`

func (q *Queries) DeleteSession(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteSession, id)
	return err
}

const deleteStartingStocks = `-- name: DeleteStartingStocks :exec
DELETE FROM game_starting_stocks WHERE game_id = ?
`

func (q *Queries) DeleteStartingStocks(ctx context.Context, gameID int64) error {
	_, err := q.db.ExecContext(ctx, deleteStartingStocks, gameID)
	return err
}

const deleteUserSessions = `-- name: DeleteUserSessions :exec
DELETE FROM sessions WHERE user_id = ?
`

func (q *Queries) DeleteUserSessions(ctx context.Context, userID int64) error {
	_, err := q.db.ExecContext(ctx, deleteUserSessions, userID)
	return err
}

const expireOldLimitOrders = `-- name: ExpireOldLimitOrders :exec
UPDATE limit_orders SET status = 'expired'
WHERE status = 'open' AND expires_at IS NOT NULL AND expires_at < ?1
`

func (q *Queries) ExpireOldLimitOrders(ctx context.Context, today sql.NullString) error {
	_, err := q.db.ExecContext(ctx, expireOldLimitOrders, today)
	return err
}

const fillLimitOrder = `-- name: FillLimitOrder :exec
UPDATE limit_orders SET status = 'filled', filled_at = datetime('now') WHERE id = ?
`

func (q *Queries) FillLimitOrder(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, fillLimitOrder, id)
	return err
}

const finishExpiredGames = `-- name: FinishExpiredGames :exec
UPDATE games SET status = 'finished', updated_at = datetime('now')
WHERE status = 'active' AND end_date < ?
`

func (q *Queries) FinishExpiredGames(ctx context.Context, endDate string) error {
	_, err := q.db.ExecContext(ctx, finishExpiredGames, endDate)
	return err
}

const getAchievementByKey = `-- name: GetAchievementByKey :one
SELECT id, "key", name, description, icon FROM achievements WHERE key = ?
`

func (q *Queries) GetAchievementByKey(ctx context.Context, key string) (Achievement, error) {
	row := q.db.QueryRowContext(ctx, getAchievementByKey, key)
	var i Achievement
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Name,
		&i.Description,
		&i.Icon,
	)
	return i, err
}

const getAvatar = `-- name: GetAvatar :one
SELECT id, "key", name, image_path, category, achievement_key, sort_order FROM avatars WHERE id = ?
`

func (q *Queries) GetAvatar(ctx context.Context, id int64) (Avatar, error) {
	row := q.db.QueryRowContext(ctx, getAvatar, id)
	var i Avatar
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Name,
		&i.ImagePath,
		&i.Category,
		&i.AchievementKey,
		&i.SortOrder,
	)
	return i, err
}

const getExchangeRateOnDate = `-- name: GetExchangeRateOnDate :one
SELECT id, date, rate_aud_usd, created_at FROM exchange_rates WHERE date = ?
`

func (q *Queries) GetExchangeRateOnDate(ctx context.Context, date string) (ExchangeRate, error) {
	row := q.db.QueryRowContext(ctx, getExchangeRateOnDate, date)
	var i ExchangeRate
	err := row.Scan(
		&i.ID,
		&i.Date,
		&i.RateAudUsd,
		&i.CreatedAt,
	)
	return i, err
}

const getGame = `-- name: GetGame :one
SELECT id, created_by, name, description, status, markets, starting_balance, base_currency, max_participants, start_date, end_date, allow_short, trade_fee, referral_bonus_pct, recurring_interval, parent_game_id, template_id, created_at, updated_at FROM games WHERE id = ?
`

func (q *Queries) GetGame(ctx context.Context, id int64) (Game, error) {
	row := q.db.QueryRowContext(ctx, getGame, id)
	var i Game
	err := row.Scan(
		&i.ID,
		&i.CreatedBy,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.Markets,
		&i.StartingBalance,
		&i.BaseCurrency,
		&i.MaxParticipants,
		&i.StartDate,
		&i.EndDate,
		&i.AllowShort,
		&i.TradeFee,
		&i.ReferralBonusPct,
		&i.RecurringInterval,
		&i.ParentGameID,
		&i.TemplateID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getGameTemplate = `-- name: GetGameTemplate :one
SELECT id, name, description, markets, starting_balance, base_currency, duration_days, allow_short, trade_fee, is_builtin, created_by, created_at FROM game_templates WHERE id = ?
`

func (q *Queries) GetGameTemplate(ctx context.Context, id int64) (GameTemplate, error) {
	row := q.db.QueryRowContext(ctx, getGameTemplate, id)
	var i GameTemplate
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Markets,
		&i.StartingBalance,
		&i.BaseCurrency,
		&i.DurationDays,
		&i.AllowShort,
		&i.TradeFee,
		&i.IsBuiltin,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getHolding = `-- name: GetHolding :one
SELECT id, participant_id, stock_id, quantity, avg_cost, current_value, updated_at FROM holdings WHERE participant_id = ? AND stock_id = ?
`

type GetHoldingParams struct {
	ParticipantID int64
	StockID       int64
}

func (q *Queries) GetHolding(ctx context.Context, arg GetHoldingParams) (Holding, error) {
	row := q.db.QueryRowContext(ctx, getHolding, arg.ParticipantID, arg.StockID)
	var i Holding
	err := row.Scan(
		&i.ID,
		&i.ParticipantID,
		&i.StockID,
		&i.Quantity,
		&i.AvgCost,
		&i.CurrentValue,
		&i.UpdatedAt,
	)
	return i, err
}

const getInviteByCode = `-- name: GetInviteByCode :one
SELECT id, game_id, code, created_by, max_uses, use_count, expires_at, created_at FROM game_invites WHERE code = ?
`

func (q *Queries) GetInviteByCode(ctx context.Context, code string) (GameInvite, error) {
	row := q.db.QueryRowContext(ctx, getInviteByCode, code)
	var i GameInvite
	err := row.Scan(
		&i.ID,
		&i.GameID,
		&i.Code,
		&i.CreatedBy,
		&i.MaxUses,
		&i.UseCount,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getLatestExchangeRate = `-- name: GetLatestExchangeRate :one
SELECT id, date, rate_aud_usd, created_at FROM exchange_rates ORDER BY date DESC LIMIT 1
`

func (q *Queries) GetLatestExchangeRate(ctx context.Context) (ExchangeRate, error) {
	row := q.db.QueryRowContext(ctx, getLatestExchangeRate)
	var i ExchangeRate
	err := row.Scan(
		&i.ID,
		&i.Date,
		&i.RateAudUsd,
		&i.CreatedAt,
	)
	return i, err
}

const getLatestFetchLog = `-- name: GetLatestFetchLog :one
SELECT id, market, status, stocks_updated, error_msg, duration_ms, created_at FROM price_fetch_log
WHERE market = ?
ORDER BY created_at DESC LIMIT 1
`

func (q *Queries) GetLatestFetchLog(ctx context.Context, market string) (PriceFetchLog, error) {
	row := q.db.QueryRowContext(ctx, getLatestFetchLog, market)
	var i PriceFetchLog
	err := row.Scan(
		&i.ID,
		&i.Market,
		&i.Status,
		&i.StocksUpdated,
		&i.ErrorMsg,
		&i.DurationMs,
		&i.CreatedAt,
	)
	return i, err
}

const getLatestPrice = `-- name: GetLatestPrice :one
SELECT id, stock_id, date, open, high, low, close, volume, created_at FROM stock_prices
WHERE stock_id = ?
ORDER BY date DESC LIMIT 1
`

func (q *Queries) GetLatestPrice(ctx context.Context, stockID int64) (StockPrice, error) {
	row := q.db.QueryRowContext(ctx, getLatestPrice, stockID)
	var i StockPrice
	err := row.Scan(
		&i.ID,
		&i.StockID,
		&i.Date,
		&i.Open,
		&i.High,
		&i.Low,
		&i.Close,
		&i.Volume,
		&i.CreatedAt,
	)
	return i, err
}

const getLatestPriceDate = `-- name: GetLatestPriceDate :one
SELECT MAX(date) AS latest_date FROM stock_prices
WHERE stock_id IN (SELECT id FROM stocks WHERE market = ?)
`

func (q *Queries) GetLatestPriceDate(ctx context.Context, market string) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, getLatestPriceDate, market)
	var latest_date interface{}
	err := row.Scan(&latest_date)
	return latest_date, err
}

const getLimitOrder = `-- name: GetLimitOrder :one
SELECT id, participant_id, stock_id, type, quantity, limit_price, status, created_at, expires_at, filled_at FROM limit_orders WHERE id = ?
`

func (q *Queries) GetLimitOrder(ctx context.Context, id int64) (LimitOrder, error) {
	row := q.db.QueryRowContext(ctx, getLimitOrder, id)
	var i LimitOrder
	err := row.Scan(
		&i.ID,
		&i.ParticipantID,
		&i.StockID,
		&i.Type,
		&i.Quantity,
		&i.LimitPrice,
		&i.Status,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.FilledAt,
	)
	return i, err
}

const getOldestPriceDate = `-- name: GetOldestPriceDate :one
SELECT CAST(COALESCE(MIN(date), '') AS TEXT) AS oldest_date FROM stock_prices
`

func (q *Queries) GetOldestPriceDate(ctx context.Context) (string, error) {
	row := q.db.QueryRowContext(ctx, getOldestPriceDate)
	var oldest_date string
	err := row.Scan(&oldest_date)
	return oldest_date, err
}

const getParticipant = `-- name: GetParticipant :one
SELECT id, game_id, user_id, cash_balance, portfolio_value, is_public, joined_at FROM participants WHERE id = ?
`

func (q *Queries) GetParticipant(ctx context.Context, id int64) (Participant, error) {
	row := q.db.QueryRowContext(ctx, getParticipant, id)
	var i Participant
	err := row.Scan(
		&i.ID,
		&i.GameID,
		&i.UserID,
		&i.CashBalance,
		&i.PortfolioValue,
		&i.IsPublic,
		&i.JoinedAt,
	)
	return i, err
}

const getParticipantByGameAndUser = `-- name: GetParticipantByGameAndUser :one
SELECT id, game_id, user_id, cash_balance, portfolio_value, is_public, joined_at FROM participants WHERE game_id = ? AND user_id = ?
`

type GetParticipantByGameAndUserParams struct {
	GameID int64
	UserID int64
}

func (q *Queries) GetParticipantByGameAndUser(ctx context.Context, arg GetParticipantByGameAndUserParams) (Participant, error) {
	row := q.db.QueryRowContext(ctx, getParticipantByGameAndUser, arg.GameID, arg.UserID)
	var i Participant
	err := row.Scan(
		&i.ID,
		&i.GameID,
		&i.UserID,
		&i.CashBalance,
		&i.PortfolioValue,
		&i.IsPublic,
		&i.JoinedAt,
	)
	return i, err
}

const getPriceOnDate = `-- name: GetPriceOnDate :one
SELECT id, stock_id, date, open, high, low, close, volume, created_at FROM stock_prices
WHERE stock_id = ? AND date = ?
`

type GetPriceOnDateParams struct {
	StockID int64
	Date    string
}

func (q *Queries) GetPriceOnDate(ctx context.Context, arg GetPriceOnDateParams) (StockPrice, error) {
	row := q.db.QueryRowContext(ctx, getPriceOnDate, arg.StockID, arg.Date)
	var i StockPrice
	err := row.Scan(
		&i.ID,
		&i.StockID,
		&i.Date,
		&i.Open,
		&i.High,
		&i.Low,
		&i.Close,
		&i.Volume,
		&i.CreatedAt,
	)
	return i, err
}

const getSession = `-- name: GetSession :one
SELECT id, user_id, expires_at, created_at FROM sessions
WHERE id = ? AND expires_at > datetime('now')
`

func (q *Queries) GetSession(ctx context.Context, id string) (Session, error) {
	row := q.db.QueryRowContext(ctx, getSession, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getStock = `-- name: GetStock :one
SELECT id, symbol, name, market, sector, currency, is_active, created_at FROM stocks WHERE id = ?
`

func (q *Queries) GetStock(ctx context.Context, id int64) (Stock, error) {
	row := q.db.QueryRowContext(ctx, getStock, id)
	var i Stock
	err := row.Scan(
		&i.ID,
		&i.Symbol,
		&i.Name,
		&i.Market,
		&i.Sector,
		&i.Currency,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const getStockBySymbol = `-- name: GetStockBySymbol :one
SELECT id, symbol, name, market, sector, currency, is_active, created_at FROM stocks WHERE symbol = ? AND market = ?
`

type GetStockBySymbolParams struct {
	Symbol string
	Market string
}

func (q *Queries) GetStockBySymbol(ctx context.Context, arg GetStockBySymbolParams) (Stock, error) {
	row := q.db.QueryRowContext(ctx, getStockBySymbol, arg.Symbol, arg.Market)
	var i Stock
	err := row.Scan(
		&i.ID,
		&i.Symbol,
		&i.Name,
		&i.Market,
		&i.Sector,
		&i.Currency,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT id, google_id, email, name, picture_url, is_admin, avatar_id, created_at, last_login, deleted_at FROM users WHERE id = ?
`

func (q *Queries) GetUser(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRowContext(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.GoogleID,
		&i.Email,
		&i.Name,
		&i.PictureUrl,
		&i.IsAdmin,
		&i.AvatarID,
		&i.CreatedAt,
		&i.LastLogin,
		&i.DeletedAt,
	)
	return i, err
}

const getUserAvatarPath = `-- name: GetUserAvatarPath :one
SELECT COALESCE(a.image_path, '') AS avatar_path
FROM users u
LEFT JOIN avatars a ON a.id = u.avatar_id
WHERE u.id = ?
`

func (q *Queries) GetUserAvatarPath(ctx context.Context, id int64) (string, error) {
	row := q.db.QueryRowContext(ctx, getUserAvatarPath, id)
	var avatar_path string
	err := row.Scan(&avatar_path)
	return avatar_path, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, google_id, email, name, picture_url, is_admin, avatar_id, created_at, last_login, deleted_at FROM users WHERE email = ?
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.GoogleID,
		&i.Email,
		&i.Name,
		&i.PictureUrl,
		&i.IsAdmin,
		&i.AvatarID,
		&i.CreatedAt,
		&i.LastLogin,
		&i.DeletedAt,
	)
	return i, err
}

const getUserTradeCount = `-- name: GetUserTradeCount :one

SELECT COUNT(*) FROM transactions t
JOIN participants p ON p.id = t.participant_id
WHERE p.user_id = ?
`

// =============================================================================
// Admin - User Activity (Feature 22)
// =============================================================================
func (q *Queries) GetUserTradeCount(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, getUserTradeCount, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const grantAchievement = `-- name: GrantAchievement :exec
INSERT OR IGNORE INTO user_achievements (user_id, achievement_id, game_id)
VALUES (?, ?, ?)
`

type GrantAchievementParams struct {
	UserID        int64
	AchievementID int64
	GameID        sql.NullInt64
}

func (q *Queries) GrantAchievement(ctx context.Context, arg GrantAchievementParams) error {
	_, err := q.db.ExecContext(ctx, grantAchievement, arg.UserID, arg.AchievementID, arg.GameID)
	return err
}

const hasAchievement = `-- name: HasAchievement :one
SELECT COUNT(*) FROM user_achievements
WHERE user_id = ? AND achievement_id = ? AND (game_id = ? OR game_id IS NULL)
`

type HasAchievementParams struct {
	UserID        int64
	AchievementID int64
	GameID        sql.NullInt64
}

func (q *Queries) HasAchievement(ctx context.Context, arg HasAchievementParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, hasAchievement, arg.UserID, arg.AchievementID, arg.GameID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const incrementInviteUse = `-- name: IncrementInviteUse :exec
UPDATE game_invites SET use_count = use_count + 1 WHERE id = ?
`

func (q *Queries) IncrementInviteUse(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, incrementInviteUse, id)
	return err
}

const insertActivity = `-- name: InsertActivity :exec

INSERT INTO activity_feed (game_id, user_id, action, detail, is_public)
VALUES (?, ?, ?, ?, ?)
`

type InsertActivityParams struct {
	GameID   int64
	UserID   int64
	Action   string
	Detail   string
	IsPublic int64
}

// =============================================================================
// Activity Feed (Feature 10)
// =============================================================================
func (q *Queries) InsertActivity(ctx context.Context, arg InsertActivityParams) error {
	_, err := q.db.ExecContext(ctx, insertActivity,
		arg.GameID,
		arg.UserID,
		arg.Action,
		arg.Detail,
		arg.IsPublic,
	)
	return err
}

const insertFetchLog = `-- name: InsertFetchLog :exec

INSERT INTO price_fetch_log (market, status, stocks_updated, error_msg, duration_ms)
VALUES (?, ?, ?, ?, ?)
`

type InsertFetchLogParams struct {
	Market        string
	Status        string
	StocksUpdated int64
	ErrorMsg      sql.NullString
	DurationMs    sql.NullInt64
}

// =============================================================================
// Price Fetch Log
// =============================================================================
func (q *Queries) InsertFetchLog(ctx context.Context, arg InsertFetchLogParams) error {
	_, err := q.db.ExecContext(ctx, insertFetchLog,
		arg.Market,
		arg.Status,
		arg.StocksUpdated,
		arg.ErrorMsg,
		arg.DurationMs,
	)
	return err
}

const insertReferralBonus = `-- name: InsertReferralBonus :exec

INSERT OR IGNORE INTO referral_bonuses (invite_id, referrer_id, referred_id, game_id, bonus_amount)
VALUES (?, ?, ?, ?, ?)
`

type InsertReferralBonusParams struct {
	InviteID    int64
	ReferrerID  int64
	ReferredID  int64
	GameID      int64
	BonusAmount int64
}

// =============================================================================
// Referral Bonuses
// =============================================================================
func (q *Queries) InsertReferralBonus(ctx context.Context, arg InsertReferralBonusParams) error {
	_, err := q.db.ExecContext(ctx, insertReferralBonus,
		arg.InviteID,
		arg.ReferrerID,
		arg.ReferredID,
		arg.GameID,
		arg.BonusAmount,
	)
	return err
}

const insertStock = `-- name: InsertStock :exec

INSERT OR IGNORE INTO stocks (symbol, name, market, sector, currency)
VALUES (?, ?, ?, ?, ?)
`

type InsertStockParams struct {
	Symbol   string
	Name     string
	Market   string
	Sector   string
	Currency string
}

// =============================================================================
// Stocks
// =============================================================================
func (q *Queries) InsertStock(ctx context.Context, arg InsertStockParams) error {
	_, err := q.db.ExecContext(ctx, insertStock,
		arg.Symbol,
		arg.Name,
		arg.Market,
		arg.Sector,
		arg.Currency,
	)
	return err
}

const insertTransaction = `-- name: InsertTransaction :one

INSERT INTO transactions (participant_id, stock_id, type, quantity, price, total, converted_total, exchange_rate_used, fee)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, participant_id, stock_id, type, quantity, price, total, converted_total, exchange_rate_used, fee, created_at
`

type InsertTransactionParams struct {
	ParticipantID    int64
	StockID          int64
	Type             string
	Quantity         int64
	Price            int64
	Total            int64
	ConvertedTotal   int64
	ExchangeRateUsed int64
	Fee              int64
}

// =============================================================================
// Transactions
// =============================================================================
func (q *Queries) InsertTransaction(ctx context.Context, arg InsertTransactionParams) (Transaction, error) {
	row := q.db.QueryRowContext(ctx, insertTransaction,
		arg.ParticipantID,
		arg.StockID,
		arg.Type,
		arg.Quantity,
		arg.Price,
		arg.Total,
		arg.ConvertedTotal,
		arg.ExchangeRateUsed,
		arg.Fee,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.ParticipantID,
		&i.StockID,
		&i.Type,
		&i.Quantity,
		&i.Price,
		&i.Total,
		&i.ConvertedTotal,
		&i.ExchangeRateUsed,
		&i.Fee,
		&i.CreatedAt,
	)
	return i, err
}

const isOnWatchlist = `-- name: IsOnWatchlist :one
SELECT COUNT(*) FROM watchlist WHERE participant_id = ? AND stock_id = ?
`

type IsOnWatchlistParams struct {
	ParticipantID int64
	StockID       int64
}

func (q *Queries) IsOnWatchlist(ctx context.Context, arg IsOnWatchlistParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, isOnWatchlist, arg.ParticipantID, arg.StockID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const joinGame = `-- name: JoinGame :one

INSERT INTO participants (game_id, user_id, cash_balance, portfolio_value)
VALUES (?, ?, ?, ?)
RETURNING id, game_id, user_id, cash_balance, portfolio_value, is_public, joined_at
`

type JoinGameParams struct {
	GameID         int64
	UserID         int64
	CashBalance    int64
	PortfolioValue int64
}

// =============================================================================
// Participants
// =============================================================================
func (q *Queries) JoinGame(ctx context.Context, arg JoinGameParams) (Participant, error) {
	row := q.db.QueryRowContext(ctx, joinGame,
		arg.GameID,
		arg.UserID,
		arg.CashBalance,
		arg.PortfolioValue,
	)
	var i Participant
	err := row.Scan(
		&i.ID,
		&i.GameID,
		&i.UserID,
		&i.CashBalance,
		&i.PortfolioValue,
		&i.IsPublic,
		&i.JoinedAt,
	)
	return i, err
}

const listAchievements = `-- name: ListAchievements :many
SELECT id, "key", name, description, icon FROM achievements ORDER BY id
`

func (q *Queries) ListAchievements(ctx context.Context) ([]Achievement, error) {
	rows, err := q.db.QueryContext(ctx, listAchievements)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Achievement
	for rows.Next() {
		var i Achievement
		if err := rows.Scan(
			&i.ID,
			&i.Key,
			&i.Name,
			&i.Description,
			&i.Icon,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveGames = `-- name: ListActiveGames :many
SELECT id, created_by, name, description, status, markets, starting_balance, base_currency, max_participants, start_date, end_date, allow_short, trade_fee, referral_bonus_pct, recurring_interval, parent_game_id, template_id, created_at, updated_at FROM games WHERE status IN ('pending', 'active') ORDER BY start_date ASC
`

func (q *Queries) ListActiveGames(ctx context.Context) ([]Game, error) {
	rows, err := q.db.QueryContext(ctx, listActiveGames)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Game
	for rows.Next() {
		var i Game
		if err := rows.Scan(
			&i.ID,
			&i.CreatedBy,
			&i.Name,
			&i.Description,
			&i.Status,
			&i.Markets,
			&i.StartingBalance,
			&i.BaseCurrency,
			&i.MaxParticipants,
			&i.StartDate,
			&i.EndDate,
			&i.AllowShort,
			&i.TradeFee,
			&i.ReferralBonusPct,
			&i.RecurringInterval,
			&i.ParentGameID,
			&i.TemplateID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveParticipants = `-- name: ListActiveParticipants :many

SELECT p.id, p.game_id, p.user_id, p.cash_balance, p.portfolio_value, p.is_public, p.joined_at, g.base_currency
FROM participants p
JOIN games g ON g.id = p.game_id
WHERE g.status = 'active'
`

type ListActiveParticipantsRow struct {
	ID             int64
	GameID         int64
	UserID         int64
	CashBalance    int64
	PortfolioValue int64
	IsPublic       int64
	JoinedAt       string
	BaseCurrency   string
}

// =============================================================================
// Active Participants (for revaluation)
// =============================================================================
func (q *Queries) ListActiveParticipants(ctx context.Context) ([]ListActiveParticipantsRow, error) {
	rows, err := q.db.QueryContext(ctx, listActiveParticipants)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActiveParticipantsRow
	for rows.Next() {
		var i ListActiveParticipantsRow
		if err := rows.Scan(
			&i.ID,
			&i.GameID,
			&i.UserID,
			&i.CashBalance,
			&i.PortfolioValue,
			&i.IsPublic,
			&i.JoinedAt,
			&i.BaseCurrency,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActivityFeed = `-- name: ListActivityFeed :many
SELECT af.id, af.game_id, af.user_id, af."action", af.detail, af.is_public, af.created_at, u.name AS user_name, u.picture_url AS user_picture
FROM activity_feed af
JOIN users u ON u.id = af.user_id
WHERE af.game_id = ? AND af.is_public = 1
ORDER BY af.created_at DESC
LIMIT ? OFFSET ?
`

type ListActivityFeedParams struct {
	GameID int64
	Limit  int64
	Offset int64
}

type ListActivityFeedRow struct {
	ID          int64
	GameID      int64
	UserID      int64
	Action      string
	Detail      string
	IsPublic    int64
	CreatedAt   string
	UserName    string
	UserPicture sql.NullString
}

func (q *Queries) ListActivityFeed(ctx context.Context, arg ListActivityFeedParams) ([]ListActivityFeedRow, error) {
	rows, err := q.db.QueryContext(ctx, listActivityFeed, arg.GameID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActivityFeedRow
	for rows.Next() {
		var i ListActivityFeedRow
		if err := rows.Scan(
			&i.ID,
			&i.GameID,
			&i.UserID,
			&i.Action,
			&i.Detail,
			&i.IsPublic,
			&i.CreatedAt,
			&i.UserName,
			&i.UserPicture,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllActiveHoldings = `-- name: ListAllActiveHoldings :many
SELECT h.id, h.participant_id, h.stock_id, h.quantity, h.avg_cost, h.current_value, h.updated_at, s.symbol, s.market, s.currency, p.game_id
FROM holdings h
JOIN stocks s ON s.id = h.stock_id
JOIN participants p ON p.id = h.participant_id
JOIN games g ON g.id = p.game_id
WHERE g.status = 'active'
`

type ListAllActiveHoldingsRow struct {
	ID            int64
	ParticipantID int64
	StockID       int64
	Quantity      int64
	AvgCost       int64
	CurrentValue  int64
	UpdatedAt     string
	Symbol        string
	Market        string
	Currency      string
	GameID        int64
}

func (q *Queries) ListAllActiveHoldings(ctx context.Context) ([]ListAllActiveHoldingsRow, error) {
	rows, err := q.db.QueryContext(ctx, listAllActiveHoldings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllActiveHoldingsRow
	for rows.Next() {
		var i ListAllActiveHoldingsRow
		if err := rows.Scan(
			&i.ID,
			&i.ParticipantID,
			&i.StockID,
			&i.Quantity,
			&i.AvgCost,
			&i.CurrentValue,
			&i.UpdatedAt,
			&i.Symbol,
			&i.Market,
			&i.Currency,
			&i.GameID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllOpenOrders = `-- name: ListAllOpenOrders :many
SELECT lo.id, lo.participant_id, lo.stock_id, lo.type, lo.quantity, lo.limit_price, lo.status, lo.created_at, lo.expires_at, lo.filled_at, s.symbol, s.market, s.currency, p.game_id
FROM limit_orders lo
JOIN stocks s ON s.id = lo.stock_id
JOIN participants p ON p.id = lo.participant_id
JOIN games g ON g.id = p.game_id
WHERE lo.status = 'open' AND g.status = 'active'
`

type ListAllOpenOrdersRow struct {
	ID            int64
	ParticipantID int64
	StockID       int64
	Type          string
	Quantity      int64
	LimitPrice    int64
	Status        string
	CreatedAt     string
	ExpiresAt     sql.NullString
	FilledAt      sql.NullString
	Symbol        string
	Market        string
	Currency      string
	GameID        int64
}

func (q *Queries) ListAllOpenOrders(ctx context.Context) ([]ListAllOpenOrdersRow, error) {
	rows, err := q.db.QueryContext(ctx, listAllOpenOrders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllOpenOrdersRow
	for rows.Next() {
		var i ListAllOpenOrdersRow
		if err := rows.Scan(
			&i.ID,
			&i.ParticipantID,
			&i.StockID,
			&i.Type,
			&i.Quantity,
			&i.LimitPrice,
			&i.Status,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.FilledAt,
			&i.Symbol,
			&i.Market,
			&i.Currency,
			&i.GameID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllTransactions = `-- name: ListAllTransactions :many

SELECT t.id, t.participant_id, t.stock_id, t.type, t.quantity, t.price, t.total, t.converted_total, t.exchange_rate_used, t.fee, t.created_at, s.symbol, s.name AS stock_name, s.market, s.currency
FROM transactions t
JOIN stocks s ON s.id = t.stock_id
WHERE t.participant_id = ?
ORDER BY t.created_at ASC
`

type ListAllTransactionsRow struct {
	ID               int64
	ParticipantID    int64
	StockID          int64
	Type             string
	Quantity         int64
	Price            int64
	Total            int64
	ConvertedTotal   int64
	ExchangeRateUsed int64
	Fee              int64
	CreatedAt        string
	Symbol           string
	StockName        string
	Market           string
	Currency         string
}

// =============================================================================
// Trade Analytics (Feature 15)
// =============================================================================
func (q *Queries) ListAllTransactions(ctx context.Context, participantID int64) ([]ListAllTransactionsRow, error) {
	rows, err := q.db.QueryContext(ctx, listAllTransactions, participantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllTransactionsRow
	for rows.Next() {
		var i ListAllTransactionsRow
		if err := rows.Scan(
			&i.ID,
			&i.ParticipantID,
			&i.StockID,
			&i.Type,
			&i.Quantity,
			&i.Price,
			&i.Total,
			&i.ConvertedTotal,
			&i.ExchangeRateUsed,
			&i.Fee,
			&i.CreatedAt,
			&i.Symbol,
			&i.StockName,
			&i.Market,
			&i.Currency,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllTransactionsForExport = `-- name: ListAllTransactionsForExport :many

SELECT t.created_at, t.type, s.symbol, s.name AS stock_name, s.market,
    t.quantity, t.price, t.total, t.converted_total, t.exchange_rate_used, t.fee
FROM transactions t
JOIN stocks s ON s.id = t.stock_id
WHERE t.participant_id = ?
ORDER BY t.created_at ASC
`

type ListAllTransactionsForExportRow struct {
	CreatedAt        string
	Type             string
	Symbol           string
	StockName        string
	Market           string
	Quantity         int64
	Price            int64
	Total            int64
	ConvertedTotal   int64
	ExchangeRateUsed int64
	Fee              int64
}

// =============================================================================
// CSV Export Helpers (Feature 23)
// =============================================================================
func (q *Queries) ListAllTransactionsForExport(ctx context.Context, participantID int64) ([]ListAllTransactionsForExportRow, error) {
	rows, err := q.db.QueryContext(ctx, listAllTransactionsForExport, participantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllTransactionsForExportRow
	for rows.Next() {
		var i ListAllTransactionsForExportRow
		if err := rows.Scan(
			&i.CreatedAt,
			&i.Type,
			&i.Symbol,
			&i.StockName,
			&i.Market,
			&i.Quantity,
			&i.Price,
			&i.Total,
			&i.ConvertedTotal,
			&i.ExchangeRateUsed,
			&i.Fee,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAvatars = `-- name: ListAvatars :many
SELECT id, "key", name, image_path, category, achievement_key, sort_order FROM avatars ORDER BY sort_order, id
`

func (q *Queries) ListAvatars(ctx context.Context) ([]Avatar, error) {
	rows, err := q.db.QueryContext(ctx, listAvatars)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Avatar
	for rows.Next() {
		var i Avatar
		if err := rows.Scan(
			&i.ID,
			&i.Key,
			&i.Name,
			&i.ImagePath,
			&i.Category,
			&i.AchievementKey,
			&i.SortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listContactMessages = `-- name: ListContactMessages :many
SELECT id, user_id, name, email, message, is_read, created_at FROM contact_messages
ORDER BY created_at DESC
LIMIT ? OFFSET ?
`

type ListContactMessagesParams struct {
	Limit  int64
	Offset int64
}

func (q *Queries) ListContactMessages(ctx context.Context, arg ListContactMessagesParams) ([]ContactMessage, error) {
	rows, err := q.db.QueryContext(ctx, listContactMessages, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ContactMessage
	for rows.Next() {
		var i ContactMessage
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Email,
			&i.Message,
			&i.IsRead,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFetchLogs = `-- name: ListFetchLogs :many
SELECT id, market, status, stocks_updated, error_msg, duration_ms, created_at FROM price_fetch_log
ORDER BY created_at DESC LIMIT 50
`

func (q *Queries) ListFetchLogs(ctx context.Context) ([]PriceFetchLog, error) {
	rows, err := q.db.QueryContext(ctx, listFetchLogs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PriceFetchLog
	for rows.Next() {
		var i PriceFetchLog
		if err := rows.Scan(
			&i.ID,
			&i.Market,
			&i.Status,
			&i.StocksUpdated,
			&i.ErrorMsg,
			&i.DurationMs,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFinishedGames = `-- name: ListFinishedGames :many

SELECT id, created_by, name, description, status, markets, starting_balance, base_currency, max_participants, start_date, end_date, allow_short, trade_fee, referral_bonus_pct, recurring_interval, parent_game_id, template_id, created_at, updated_at FROM games WHERE status IN ('finished', 'cancelled')
ORDER BY end_date DESC
LIMIT ? OFFSET ?
`

type ListFinishedGamesParams struct {
	Limit  int64
	Offset int64
}

// =============================================================================
// Game History (Feature 20)
// =============================================================================
func (q *Queries) ListFinishedGames(ctx context.Context, arg ListFinishedGamesParams) ([]Game, error) {
	rows, err := q.db.QueryContext(ctx, listFinishedGames, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Game
	for rows.Next() {
		var i Game
		if err := rows.Scan(
			&i.ID,
			&i.CreatedBy,
			&i.Name,
			&i.Description,
			&i.Status,
			&i.Markets,
			&i.StartingBalance,
			&i.BaseCurrency,
			&i.MaxParticipants,
			&i.StartDate,
			&i.EndDate,
			&i.AllowShort,
			&i.TradeFee,
			&i.ReferralBonusPct,
			&i.RecurringInterval,
			&i.ParentGameID,
			&i.TemplateID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFinishedRecurringGames = `-- name: ListFinishedRecurringGames :many

SELECT id, created_by, name, description, status, markets, starting_balance, base_currency, max_participants, start_date, end_date, allow_short, trade_fee, referral_bonus_pct, recurring_interval, parent_game_id, template_id, created_at, updated_at FROM games
WHERE status = 'finished' AND recurring_interval IS NOT NULL
ORDER BY end_date DESC
`

// =============================================================================
// Recurring Games (Feature 17)
// =============================================================================
func (q *Queries) ListFinishedRecurringGames(ctx context.Context) ([]Game, error) {
	rows, err := q.db.QueryContext(ctx, listFinishedRecurringGames)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Game
	for rows.Next() {
		var i Game
		if err := rows.Scan(
			&i.ID,
			&i.CreatedBy,
			&i.Name,
			&i.Description,
			&i.Status,
			&i.Markets,
			&i.StartingBalance,
			&i.BaseCurrency,
			&i.MaxParticipants,
			&i.StartDate,
			&i.EndDate,
			&i.AllowShort,
			&i.TradeFee,
			&i.ReferralBonusPct,
			&i.RecurringInterval,
			&i.ParentGameID,
			&i.TemplateID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGameInvites = `-- name: ListGameInvites :many
SELECT id, game_id, code, created_by, max_uses, use_count, expires_at, created_at FROM game_invites WHERE game_id = ? ORDER BY created_at DESC
`

func (q *Queries) ListGameInvites(ctx context.Context, gameID int64) ([]GameInvite, error) {
	rows, err := q.db.QueryContext(ctx, listGameInvites, gameID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GameInvite
	for rows.Next() {
		var i GameInvite
		if err := rows.Scan(
			&i.ID,
			&i.GameID,
			&i.Code,
			&i.CreatedBy,
			&i.MaxUses,
			&i.UseCount,
			&i.ExpiresAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGameTemplates = `-- name: ListGameTemplates :many
SELECT id, name, description, markets, starting_balance, base_currency, duration_days, allow_short, trade_fee, is_builtin, created_by, created_at FROM game_templates ORDER BY is_builtin DESC, name ASC
`

func (q *Queries) ListGameTemplates(ctx context.Context) ([]GameTemplate, error) {
	rows, err := q.db.QueryContext(ctx, listGameTemplates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GameTemplate
	for rows.Next() {
		var i GameTemplate
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Markets,
			&i.StartingBalance,
			&i.BaseCurrency,
			&i.DurationDays,
			&i.AllowShort,
			&i.TradeFee,
			&i.IsBuiltin,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGamesByCreator = `-- name: ListGamesByCreator :many
SELECT id, created_by, name, description, status, markets, starting_balance, base_currency, max_participants, start_date, end_date, allow_short, trade_fee, referral_bonus_pct, recurring_interval, parent_game_id, template_id, created_at, updated_at FROM games WHERE created_by = ? ORDER BY created_at DESC
`

func (q *Queries) ListGamesByCreator(ctx context.Context, createdBy int64) ([]Game, error) {
	rows, err := q.db.QueryContext(ctx, listGamesByCreator, createdBy)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Game
	for rows.Next() {
		var i Game
		if err := rows.Scan(
			&i.ID,
			&i.CreatedBy,
			&i.Name,
			&i.Description,
			&i.Status,
			&i.Markets,
			&i.StartingBalance,
			&i.BaseCurrency,
			&i.MaxParticipants,
			&i.StartDate,
			&i.EndDate,
			&i.AllowShort,
			&i.TradeFee,
			&i.ReferralBonusPct,
			&i.RecurringInterval,
			&i.ParentGameID,
			&i.TemplateID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHoldings = `-- name: ListHoldings :many
SELECT h.id, h.participant_id, h.stock_id, h.quantity, h.avg_cost, h.current_value, h.updated_at, s.symbol, s.name AS stock_name, s.market, s.currency
FROM holdings h
JOIN stocks s ON s.id = h.stock_id
WHERE h.participant_id = ?
ORDER BY h.current_value DESC
`

type ListHoldingsRow struct {
	ID            int64
	ParticipantID int64
	StockID       int64
	Quantity      int64
	AvgCost       int64
	CurrentValue  int64
	UpdatedAt     string
	Symbol        string
	StockName     string
	Market        string
	Currency      string
}

func (q *Queries) ListHoldings(ctx context.Context, participantID int64) ([]ListHoldingsRow, error) {
	rows, err := q.db.QueryContext(ctx, listHoldings, participantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListHoldingsRow
	for rows.Next() {
		var i ListHoldingsRow
		if err := rows.Scan(
			&i.ID,
			&i.ParticipantID,
			&i.StockID,
			&i.Quantity,
			&i.AvgCost,
			&i.CurrentValue,
			&i.UpdatedAt,
			&i.Symbol,
			&i.StockName,
			&i.Market,
			&i.Currency,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHoldingsBySector = `-- name: ListHoldingsBySector :many

SELECT s.sector, SUM(h.current_value) AS total_value
FROM holdings h
JOIN stocks s ON s.id = h.stock_id
WHERE h.participant_id = ?
GROUP BY s.sector
ORDER BY total_value DESC
`

type ListHoldingsBySectorRow struct {
	Sector     string
	TotalValue sql.NullFloat64
}

// =============================================================================
// Sector Holdings (Feature 12)
// =============================================================================
func (q *Queries) ListHoldingsBySector(ctx context.Context, participantID int64) ([]ListHoldingsBySectorRow, error) {
	rows, err := q.db.QueryContext(ctx, listHoldingsBySector, participantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListHoldingsBySectorRow
	for rows.Next() {
		var i ListHoldingsBySectorRow
		if err := rows.Scan(&i.Sector, &i.TotalValue); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLobbyMessages = `-- name: ListLobbyMessages :many
SELECT lm.id, lm.user_id, lm.message, lm.created_at, u.name AS user_name, u.picture_url AS user_picture,
    COALESCE(a.image_path, '') AS avatar_path
FROM lobby_messages lm
JOIN users u ON u.id = lm.user_id
LEFT JOIN avatars a ON a.id = u.avatar_id
ORDER BY lm.created_at DESC
LIMIT ? OFFSET ?
`

type ListLobbyMessagesParams struct {
	Limit  int64
	Offset int64
}

type ListLobbyMessagesRow struct {
	ID          int64
	UserID      int64
	Message     string
	CreatedAt   string
	UserName    string
	UserPicture sql.NullString
	AvatarPath  string
}

func (q *Queries) ListLobbyMessages(ctx context.Context, arg ListLobbyMessagesParams) ([]ListLobbyMessagesRow, error) {
	rows, err := q.db.QueryContext(ctx, listLobbyMessages, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLobbyMessagesRow
	for rows.Next() {
		var i ListLobbyMessagesRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Message,
			&i.CreatedAt,
			&i.UserName,
			&i.UserPicture,
			&i.AvatarPath,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMessages = `-- name: ListMessages :many
SELECT gm.id, gm.game_id, gm.user_id, gm.message, gm.created_at, u.name AS user_name, u.picture_url AS user_picture
FROM game_messages gm
JOIN users u ON u.id = gm.user_id
WHERE gm.game_id = ?
ORDER BY gm.created_at DESC
LIMIT ? OFFSET ?
`

type ListMessagesParams struct {
	GameID int64
	Limit  int64
	Offset int64
}

type ListMessagesRow struct {
	ID          int64
	GameID      int64
	UserID      int64
	Message     string
	CreatedAt   string
	UserName    string
	UserPicture sql.NullString
}

func (q *Queries) ListMessages(ctx context.Context, arg ListMessagesParams) ([]ListMessagesRow, error) {
	rows, err := q.db.QueryContext(ctx, listMessages, arg.GameID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMessagesRow
	for rows.Next() {
		var i ListMessagesRow
		if err := rows.Scan(
			&i.ID,
			&i.GameID,
			&i.UserID,
			&i.Message,
			&i.CreatedAt,
			&i.UserName,
			&i.UserPicture,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMostActiveUsers = `-- name: ListMostActiveUsers :many
SELECT u.id, u.name, u.email, u.picture_url, u.last_login,
    (SELECT COUNT(*) FROM transactions t JOIN participants p ON p.id = t.participant_id WHERE p.user_id = u.id) AS trade_count,
    (SELECT COUNT(*) FROM participants p2 WHERE p2.user_id = u.id) AS game_count
FROM users u
ORDER BY trade_count DESC
LIMIT 50
`

type ListMostActiveUsersRow struct {
	ID         int64
	Name       string
	Email      string
	PictureUrl sql.NullString
	LastLogin  string
	TradeCount int64
	GameCount  int64
}

func (q *Queries) ListMostActiveUsers(ctx context.Context) ([]ListMostActiveUsersRow, error) {
	rows, err := q.db.QueryContext(ctx, listMostActiveUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMostActiveUsersRow
	for rows.Next() {
		var i ListMostActiveUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.PictureUrl,
			&i.LastLogin,
			&i.TradeCount,
			&i.GameCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNotifications = `-- name: ListNotifications :many
SELECT id, user_id, game_id, type, title, message, is_read, created_at FROM notifications
WHERE user_id = ?
ORDER BY created_at DESC
LIMIT ? OFFSET ?
`

type ListNotificationsParams struct {
	UserID int64
	Limit  int64
	Offset int64
}

func (q *Queries) ListNotifications(ctx context.Context, arg ListNotificationsParams) ([]Notification, error) {
	rows, err := q.db.QueryContext(ctx, listNotifications, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Notification
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.GameID,
			&i.Type,
			&i.Title,
			&i.Message,
			&i.IsRead,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOpenLimitOrders = `-- name: ListOpenLimitOrders :many
SELECT lo.id, lo.participant_id, lo.stock_id, lo.type, lo.quantity, lo.limit_price, lo.status, lo.created_at, lo.expires_at, lo.filled_at, s.symbol, s.name AS stock_name, s.market, s.currency
FROM limit_orders lo
JOIN stocks s ON s.id = lo.stock_id
WHERE lo.participant_id = ? AND lo.status = 'open'
ORDER BY lo.created_at DESC
`

type ListOpenLimitOrdersRow struct {
	ID            int64
	ParticipantID int64
	StockID       int64
	Type          string
	Quantity      int64
	LimitPrice    int64
	Status        string
	CreatedAt     string
	ExpiresAt     sql.NullString
	FilledAt      sql.NullString
	Symbol        string
	StockName     string
	Market        string
	Currency      string
}

func (q *Queries) ListOpenLimitOrders(ctx context.Context, participantID int64) ([]ListOpenLimitOrdersRow, error) {
	rows, err := q.db.QueryContext(ctx, listOpenLimitOrders, participantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOpenLimitOrdersRow
	for rows.Next() {
		var i ListOpenLimitOrdersRow
		if err := rows.Scan(
			&i.ID,
			&i.ParticipantID,
			&i.StockID,
			&i.Type,
			&i.Quantity,
			&i.LimitPrice,
			&i.Status,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.FilledAt,
			&i.Symbol,
			&i.StockName,
			&i.Market,
			&i.Currency,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listParticipantsByGame = `-- name: ListParticipantsByGame :many
SELECT p.id, p.game_id, p.user_id, p.cash_balance, p.portfolio_value, p.is_public, p.joined_at, u.name AS user_name, u.picture_url AS user_picture
FROM participants p
JOIN users u ON u.id = p.user_id
WHERE p.game_id = ?
ORDER BY p.portfolio_value DESC
`

type ListParticipantsByGameRow struct {
	ID             int64
	GameID         int64
	UserID         int64
	CashBalance    int64
	PortfolioValue int64
	IsPublic       int64
	JoinedAt       string
	UserName       string
	UserPicture    sql.NullString
}

func (q *Queries) ListParticipantsByGame(ctx context.Context, gameID int64) ([]ListParticipantsByGameRow, error) {
	rows, err := q.db.QueryContext(ctx, listParticipantsByGame, gameID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListParticipantsByGameRow
	for rows.Next() {
		var i ListParticipantsByGameRow
		if err := rows.Scan(
			&i.ID,
			&i.GameID,
			&i.UserID,
			&i.CashBalance,
			&i.PortfolioValue,
			&i.IsPublic,
			&i.JoinedAt,
			&i.UserName,
			&i.UserPicture,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPriceHistory = `-- name: ListPriceHistory :many
SELECT id, stock_id, date, open, high, low, close, volume, created_at FROM stock_prices
WHERE stock_id = ? AND date >= ? AND date <= ?
ORDER BY date ASC
`

type ListPriceHistoryParams struct {
	StockID int64
	Date    string
	Date_2  string
}

func (q *Queries) ListPriceHistory(ctx context.Context, arg ListPriceHistoryParams) ([]StockPrice, error) {
	rows, err := q.db.QueryContext(ctx, listPriceHistory, arg.StockID, arg.Date, arg.Date_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StockPrice
	for rows.Next() {
		var i StockPrice
		if err := rows.Scan(
			&i.ID,
			&i.StockID,
			&i.Date,
			&i.Open,
			&i.High,
			&i.Low,
			&i.Close,
			&i.Volume,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublicParticipantsByGame = `-- name: ListPublicParticipantsByGame :many
SELECT p.id, p.game_id, p.user_id, p.cash_balance, p.portfolio_value, p.is_public, p.joined_at, u.name AS user_name, u.picture_url AS user_picture
FROM participants p
JOIN users u ON u.id = p.user_id
WHERE p.game_id = ? AND p.is_public = 1
ORDER BY p.portfolio_value DESC
`

type ListPublicParticipantsByGameRow struct {
	ID             int64
	GameID         int64
	UserID         int64
	CashBalance    int64
	PortfolioValue int64
	IsPublic       int64
	JoinedAt       string
	UserName       string
	UserPicture    sql.NullString
}

func (q *Queries) ListPublicParticipantsByGame(ctx context.Context, gameID int64) ([]ListPublicParticipantsByGameRow, error) {
	rows, err := q.db.QueryContext(ctx, listPublicParticipantsByGame, gameID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPublicParticipantsByGameRow
	for rows.Next() {
		var i ListPublicParticipantsByGameRow
		if err := rows.Scan(
			&i.ID,
			&i.GameID,
			&i.UserID,
			&i.CashBalance,
			&i.PortfolioValue,
			&i.IsPublic,
			&i.JoinedAt,
			&i.UserName,
			&i.UserPicture,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReferralBonuses = `-- name: ListReferralBonuses :many
SELECT rb.id, rb.invite_id, rb.referrer_id, rb.referred_id, rb.game_id, rb.bonus_amount, rb.created_at, u.name AS referred_name
FROM referral_bonuses rb
JOIN users u ON u.id = rb.referred_id
WHERE rb.referrer_id = ? AND rb.game_id = ?
ORDER BY rb.created_at DESC
`

type ListReferralBonusesParams struct {
	ReferrerID int64
	GameID     int64
}

type ListReferralBonusesRow struct {
	ID           int64
	InviteID     int64
	ReferrerID   int64
	ReferredID   int64
	GameID       int64
	BonusAmount  int64
	CreatedAt    string
	ReferredName string
}

func (q *Queries) ListReferralBonuses(ctx context.Context, arg ListReferralBonusesParams) ([]ListReferralBonusesRow, error) {
	rows, err := q.db.QueryContext(ctx, listReferralBonuses, arg.ReferrerID, arg.GameID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListReferralBonusesRow
	for rows.Next() {
		var i ListReferralBonusesRow
		if err := rows.Scan(
			&i.ID,
			&i.InviteID,
			&i.ReferrerID,
			&i.ReferredID,
			&i.GameID,
			&i.BonusAmount,
			&i.CreatedAt,
			&i.ReferredName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSnapshots = `-- name: ListSnapshots :many
SELECT id, participant_id, date, cash_balance, holdings_value, total_value FROM portfolio_snapshots
WHERE participant_id = ? AND date >= ? AND date <= ?
ORDER BY date ASC
`

type ListSnapshotsParams struct {
	ParticipantID int64
	Date          string
	Date_2        string
}

func (q *Queries) ListSnapshots(ctx context.Context, arg ListSnapshotsParams) ([]PortfolioSnapshot, error) {
	rows, err := q.db.QueryContext(ctx, listSnapshots, arg.ParticipantID, arg.Date, arg.Date_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PortfolioSnapshot
	for rows.Next() {
		var i PortfolioSnapshot
		if err := rows.Scan(
			&i.ID,
			&i.ParticipantID,
			&i.Date,
			&i.CashBalance,
			&i.HoldingsValue,
			&i.TotalValue,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSnapshotsForExport = `-- name: ListSnapshotsForExport :many
SELECT date, cash_balance, holdings_value, total_value
FROM portfolio_snapshots
WHERE participant_id = ?
ORDER BY date ASC
`

type ListSnapshotsForExportRow struct {
	Date          string
	CashBalance   int64
	HoldingsValue int64
	TotalValue    int64
}

func (q *Queries) ListSnapshotsForExport(ctx context.Context, participantID int64) ([]ListSnapshotsForExportRow, error) {
	rows, err := q.db.QueryContext(ctx, listSnapshotsForExport, participantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSnapshotsForExportRow
	for rows.Next() {
		var i ListSnapshotsForExportRow
		if err := rows.Scan(
			&i.Date,
			&i.CashBalance,
			&i.HoldingsValue,
			&i.TotalValue,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStartingStocks = `-- name: ListStartingStocks :many
SELECT gss.id, gss.game_id, gss.stock_id, gss.quantity, s.symbol, s.name AS stock_name, s.market, s.currency
FROM game_starting_stocks gss
JOIN stocks s ON s.id = gss.stock_id
WHERE gss.game_id = ?
`

type ListStartingStocksRow struct {
	ID        int64
	GameID    int64
	StockID   int64
	Quantity  int64
	Symbol    string
	StockName string
	Market    string
	Currency  string
}

func (q *Queries) ListStartingStocks(ctx context.Context, gameID int64) ([]ListStartingStocksRow, error) {
	rows, err := q.db.QueryContext(ctx, listStartingStocks, gameID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListStartingStocksRow
	for rows.Next() {
		var i ListStartingStocksRow
		if err := rows.Scan(
			&i.ID,
			&i.GameID,
			&i.StockID,
			&i.Quantity,
			&i.Symbol,
			&i.StockName,
			&i.Market,
			&i.Currency,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStocksByMarket = `-- name: ListStocksByMarket :many
SELECT id, symbol, name, market, sector, currency, is_active, created_at FROM stocks
WHERE is_active = 1 AND (market = ? OR ? = 'both')
ORDER BY symbol ASC
`

type ListStocksByMarketParams struct {
	Market  string
	Column2 interface{}
}

func (q *Queries) ListStocksByMarket(ctx context.Context, arg ListStocksByMarketParams) ([]Stock, error) {
	rows, err := q.db.QueryContext(ctx, listStocksByMarket, arg.Market, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Stock
	for rows.Next() {
		var i Stock
		if err := rows.Scan(
			&i.ID,
			&i.Symbol,
			&i.Name,
			&i.Market,
			&i.Sector,
			&i.Currency,
			&i.IsActive,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStocksMissingPrices = `-- name: ListStocksMissingPrices :many
SELECT s.id, s.symbol, s.name, s.market, s.sector, s.currency, s.is_active, s.created_at FROM stocks s
WHERE s.is_active = 1
AND s.id NOT IN (
    SELECT sp.stock_id FROM stock_prices sp WHERE sp.date = ?1
)
ORDER BY s.market, s.symbol
LIMIT 100
`

func (q *Queries) ListStocksMissingPrices(ctx context.Context, targetDate string) ([]Stock, error) {
	rows, err := q.db.QueryContext(ctx, listStocksMissingPrices, targetDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Stock
	for rows.Next() {
		var i Stock
		if err := rows.Scan(
			&i.ID,
			&i.Symbol,
			&i.Name,
			&i.Market,
			&i.Sector,
			&i.Currency,
			&i.IsActive,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactions = `-- name: ListTransactions :many
SELECT t.id, t.participant_id, t.stock_id, t.type, t.quantity, t.price, t.total, t.converted_total, t.exchange_rate_used, t.fee, t.created_at, s.symbol, s.name AS stock_name, s.market, s.currency
FROM transactions t
JOIN stocks s ON s.id = t.stock_id
WHERE t.participant_id = ?
ORDER BY t.created_at DESC
LIMIT ? OFFSET ?
`

type ListTransactionsParams struct {
	ParticipantID int64
	Limit         int64
	Offset        int64
}

type ListTransactionsRow struct {
	ID               int64
	ParticipantID    int64
	StockID          int64
	Type             string
	Quantity         int64
	Price            int64
	Total            int64
	ConvertedTotal   int64
	ExchangeRateUsed int64
	Fee              int64
	CreatedAt        string
	Symbol           string
	StockName        string
	Market           string
	Currency         string
}

func (q *Queries) ListTransactions(ctx context.Context, arg ListTransactionsParams) ([]ListTransactionsRow, error) {
	rows, err := q.db.QueryContext(ctx, listTransactions, arg.ParticipantID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTransactionsRow
	for rows.Next() {
		var i ListTransactionsRow
		if err := rows.Scan(
			&i.ID,
			&i.ParticipantID,
			&i.StockID,
			&i.Type,
			&i.Quantity,
			&i.Price,
			&i.Total,
			&i.ConvertedTotal,
			&i.ExchangeRateUsed,
			&i.Fee,
			&i.CreatedAt,
			&i.Symbol,
			&i.StockName,
			&i.Market,
			&i.Currency,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnreadNotifications = `-- name: ListUnreadNotifications :many
SELECT id, user_id, game_id, type, title, message, is_read, created_at FROM notifications
WHERE user_id = ? AND is_read = 0
ORDER BY created_at DESC
LIMIT 20
`

func (q *Queries) ListUnreadNotifications(ctx context.Context, userID int64) ([]Notification, error) {
	rows, err := q.db.QueryContext(ctx, listUnreadNotifications, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Notification
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.GameID,
			&i.Type,
			&i.Title,
			&i.Message,
			&i.IsRead,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserAchievements = `-- name: ListUserAchievements :many
SELECT ua.id, ua.user_id, ua.achievement_id, ua.game_id, ua.earned_at, a.key, a.name AS achievement_name, a.description, a.icon
FROM user_achievements ua
JOIN achievements a ON a.id = ua.achievement_id
WHERE ua.user_id = ?
ORDER BY ua.earned_at DESC
`

type ListUserAchievementsRow struct {
	ID              int64
	UserID          int64
	AchievementID   int64
	GameID          sql.NullInt64
	EarnedAt        string
	Key             string
	AchievementName string
	Description     string
	Icon            string
}

func (q *Queries) ListUserAchievements(ctx context.Context, userID int64) ([]ListUserAchievementsRow, error) {
	rows, err := q.db.QueryContext(ctx, listUserAchievements, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUserAchievementsRow
	for rows.Next() {
		var i ListUserAchievementsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.AchievementID,
			&i.GameID,
			&i.EarnedAt,
			&i.Key,
			&i.AchievementName,
			&i.Description,
			&i.Icon,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserChatMessages = `-- name: ListUserChatMessages :many

SELECT gm.message, gm.created_at, g.name AS game_name
FROM game_messages gm
JOIN games g ON g.id = gm.game_id
WHERE gm.user_id = ?
ORDER BY gm.created_at DESC
`

type ListUserChatMessagesRow struct {
	Message   string
	CreatedAt string
	GameName  string
}

// =============================================================================
// User Data Export
// =============================================================================
func (q *Queries) ListUserChatMessages(ctx context.Context, userID int64) ([]ListUserChatMessagesRow, error) {
	rows, err := q.db.QueryContext(ctx, listUserChatMessages, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUserChatMessagesRow
	for rows.Next() {
		var i ListUserChatMessagesRow
		if err := rows.Scan(&i.Message, &i.CreatedAt, &i.GameName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserGames = `-- name: ListUserGames :many
SELECT g.id, g.created_by, g.name, g.description, g.status, g.markets, g.starting_balance, g.base_currency, g.max_participants, g.start_date, g.end_date, g.allow_short, g.trade_fee, g.referral_bonus_pct, g.recurring_interval, g.parent_game_id, g.template_id, g.created_at, g.updated_at FROM games g
JOIN participants p ON p.game_id = g.id
WHERE p.user_id = ?
ORDER BY g.start_date DESC
`

func (q *Queries) ListUserGames(ctx context.Context, userID int64) ([]Game, error) {
	rows, err := q.db.QueryContext(ctx, listUserGames, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Game
	for rows.Next() {
		var i Game
		if err := rows.Scan(
			&i.ID,
			&i.CreatedBy,
			&i.Name,
			&i.Description,
			&i.Status,
			&i.Markets,
			&i.StartingBalance,
			&i.BaseCurrency,
			&i.MaxParticipants,
			&i.StartDate,
			&i.EndDate,
			&i.AllowShort,
			&i.TradeFee,
			&i.ReferralBonusPct,
			&i.RecurringInterval,
			&i.ParentGameID,
			&i.TemplateID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserParticipations = `-- name: ListUserParticipations :many
SELECT p.joined_at, p.cash_balance, p.portfolio_value,
    g.name AS game_name, g.status AS game_status
FROM participants p
JOIN games g ON g.id = p.game_id
WHERE p.user_id = ?
ORDER BY p.joined_at DESC
`

type ListUserParticipationsRow struct {
	JoinedAt       string
	CashBalance    int64
	PortfolioValue int64
	GameName       string
	GameStatus     string
}

func (q *Queries) ListUserParticipations(ctx context.Context, userID int64) ([]ListUserParticipationsRow, error) {
	rows, err := q.db.QueryContext(ctx, listUserParticipations, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUserParticipationsRow
	for rows.Next() {
		var i ListUserParticipationsRow
		if err := rows.Scan(
			&i.JoinedAt,
			&i.CashBalance,
			&i.PortfolioValue,
			&i.GameName,
			&i.GameStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT id, google_id, email, name, picture_url, is_admin, avatar_id, created_at, last_login, deleted_at FROM users ORDER BY created_at DESC
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.GoogleID,
			&i.Email,
			&i.Name,
			&i.PictureUrl,
			&i.IsAdmin,
			&i.AvatarID,
			&i.CreatedAt,
			&i.LastLogin,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWatchlist = `-- name: ListWatchlist :many
SELECT w.id, w.participant_id, w.stock_id, w.created_at, s.symbol, s.name AS stock_name, s.market, s.sector, s.currency
FROM watchlist w
JOIN stocks s ON s.id = w.stock_id
WHERE w.participant_id = ?
ORDER BY w.created_at DESC
`

type ListWatchlistRow struct {
	ID            int64
	ParticipantID int64
	StockID       int64
	CreatedAt     string
	Symbol        string
	StockName     string
	Market        string
	Sector        string
	Currency      string
}

func (q *Queries) ListWatchlist(ctx context.Context, participantID int64) ([]ListWatchlistRow, error) {
	rows, err := q.db.QueryContext(ctx, listWatchlist, participantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListWatchlistRow
	for rows.Next() {
		var i ListWatchlistRow
		if err := rows.Scan(
			&i.ID,
			&i.ParticipantID,
			&i.StockID,
			&i.CreatedAt,
			&i.Symbol,
			&i.StockName,
			&i.Market,
			&i.Sector,
			&i.Currency,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAllNotificationsRead = `-- name: MarkAllNotificationsRead :exec
UPDATE notifications SET is_read = 1 WHERE user_id = ? AND is_read = 0
`

func (q *Queries) MarkAllNotificationsRead(ctx context.Context, userID int64) error {
	_, err := q.db.ExecContext(ctx, markAllNotificationsRead, userID)
	return err
}

const markContactMessageRead = `-- name: MarkContactMessageRead :exec
UPDATE contact_messages SET is_read = 1 WHERE id = ?
`

func (q *Queries) MarkContactMessageRead(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, markContactMessageRead, id)
	return err
}

const markNotificationRead = `-- name: MarkNotificationRead :exec
UPDATE notifications SET is_read = 1 WHERE id = ? AND user_id = ?
`

type MarkNotificationReadParams struct {
	ID     int64
	UserID int64
}

func (q *Queries) MarkNotificationRead(ctx context.Context, arg MarkNotificationReadParams) error {
	_, err := q.db.ExecContext(ctx, markNotificationRead, arg.ID, arg.UserID)
	return err
}

const removeFromWatchlist = `-- name: RemoveFromWatchlist :exec
DELETE FROM watchlist WHERE participant_id = ? AND stock_id = ?
`

type RemoveFromWatchlistParams struct {
	ParticipantID int64
	StockID       int64
}

func (q *Queries) RemoveFromWatchlist(ctx context.Context, arg RemoveFromWatchlistParams) error {
	_, err := q.db.ExecContext(ctx, removeFromWatchlist, arg.ParticipantID, arg.StockID)
	return err
}

const searchStocks = `-- name: SearchStocks :many
SELECT id, symbol, name, market, sector, currency, is_active, created_at FROM stocks
WHERE is_active = 1
  AND (market = ? OR ? = 'both')
  AND (symbol LIKE ? OR name LIKE ?)
ORDER BY symbol ASC
LIMIT 20
`

type SearchStocksParams struct {
	Market  string
	Column2 interface{}
	Symbol  string
	Name    string
}

func (q *Queries) SearchStocks(ctx context.Context, arg SearchStocksParams) ([]Stock, error) {
	rows, err := q.db.QueryContext(ctx, searchStocks,
		arg.Market,
		arg.Column2,
		arg.Symbol,
		arg.Name,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Stock
	for rows.Next() {
		var i Stock
		if err := rows.Scan(
			&i.ID,
			&i.Symbol,
			&i.Name,
			&i.Market,
			&i.Sector,
			&i.Currency,
			&i.IsActive,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setAdmin = `-- name: SetAdmin :exec
UPDATE users SET is_admin = ? WHERE id = ?
`

type SetAdminParams struct {
	IsAdmin int64
	ID      int64
}

func (q *Queries) SetAdmin(ctx context.Context, arg SetAdminParams) error {
	_, err := q.db.ExecContext(ctx, setAdmin, arg.IsAdmin, arg.ID)
	return err
}

const softDeleteUser = `-- name: SoftDeleteUser :exec
UPDATE users SET
    name = 'Deleted User',
    email = 'deleted-' || CAST(id AS TEXT) || '@deleted.local',
    google_id = 'deleted-' || CAST(id AS TEXT),
    picture_url = NULL,
    deleted_at = datetime('now')
WHERE id = ?
`

func (q *Queries) SoftDeleteUser(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, softDeleteUser, id)
	return err
}

const totalReferralBonus = `-- name: TotalReferralBonus :one
SELECT COALESCE(SUM(bonus_amount), 0) FROM referral_bonuses WHERE referrer_id = ? AND game_id = ?
`

type TotalReferralBonusParams struct {
	ReferrerID int64
	GameID     int64
}

func (q *Queries) TotalReferralBonus(ctx context.Context, arg TotalReferralBonusParams) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, totalReferralBonus, arg.ReferrerID, arg.GameID)
	var coalesce interface{}
	err := row.Scan(&coalesce)
	return coalesce, err
}

const updateCashBalance = `-- name: UpdateCashBalance :exec
UPDATE participants SET cash_balance = ? WHERE id = ?
`

type UpdateCashBalanceParams struct {
	CashBalance int64
	ID          int64
}

func (q *Queries) UpdateCashBalance(ctx context.Context, arg UpdateCashBalanceParams) error {
	_, err := q.db.ExecContext(ctx, updateCashBalance, arg.CashBalance, arg.ID)
	return err
}

const updateGameSettings = `-- name: UpdateGameSettings :exec
UPDATE games SET
    name = ?, description = ?, markets = ?, starting_balance = ?,
    base_currency = ?, max_participants = ?, start_date = ?, end_date = ?,
    allow_short = ?, trade_fee = ?, updated_at = datetime('now')
WHERE id = ?
`

type UpdateGameSettingsParams struct {
	Name            string
	Description     string
	Markets         string
	StartingBalance int64
	BaseCurrency    string
	MaxParticipants sql.NullInt64
	StartDate       string
	EndDate         string
	AllowShort      int64
	TradeFee        int64
	ID              int64
}

func (q *Queries) UpdateGameSettings(ctx context.Context, arg UpdateGameSettingsParams) error {
	_, err := q.db.ExecContext(ctx, updateGameSettings,
		arg.Name,
		arg.Description,
		arg.Markets,
		arg.StartingBalance,
		arg.BaseCurrency,
		arg.MaxParticipants,
		arg.StartDate,
		arg.EndDate,
		arg.AllowShort,
		arg.TradeFee,
		arg.ID,
	)
	return err
}

const updateGameStatus = `-- name: UpdateGameStatus :exec
UPDATE games SET status = ?, updated_at = datetime('now') WHERE id = ?
`

type UpdateGameStatusParams struct {
	Status string
	ID     int64
}

func (q *Queries) UpdateGameStatus(ctx context.Context, arg UpdateGameStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateGameStatus, arg.Status, arg.ID)
	return err
}

const updateHoldingValue = `-- name: UpdateHoldingValue :exec
UPDATE holdings SET current_value = ?, updated_at = datetime('now')
WHERE id = ?
`

type UpdateHoldingValueParams struct {
	CurrentValue int64
	ID           int64
}

func (q *Queries) UpdateHoldingValue(ctx context.Context, arg UpdateHoldingValueParams) error {
	_, err := q.db.ExecContext(ctx, updateHoldingValue, arg.CurrentValue, arg.ID)
	return err
}

const updateParticipantVisibility = `-- name: UpdateParticipantVisibility :exec
UPDATE participants SET is_public = ? WHERE id = ?
`

type UpdateParticipantVisibilityParams struct {
	IsPublic int64
	ID       int64
}

func (q *Queries) UpdateParticipantVisibility(ctx context.Context, arg UpdateParticipantVisibilityParams) error {
	_, err := q.db.ExecContext(ctx, updateParticipantVisibility, arg.IsPublic, arg.ID)
	return err
}

const updatePortfolioValue = `-- name: UpdatePortfolioValue :exec
UPDATE participants SET portfolio_value = ? WHERE id = ?
`

type UpdatePortfolioValueParams struct {
	PortfolioValue int64
	ID             int64
}

func (q *Queries) UpdatePortfolioValue(ctx context.Context, arg UpdatePortfolioValueParams) error {
	_, err := q.db.ExecContext(ctx, updatePortfolioValue, arg.PortfolioValue, arg.ID)
	return err
}

const updateUserAvatar = `-- name: UpdateUserAvatar :exec
UPDATE users SET avatar_id = ? WHERE id = ?
`

type UpdateUserAvatarParams struct {
	AvatarID sql.NullInt64
	ID       int64
}

func (q *Queries) UpdateUserAvatar(ctx context.Context, arg UpdateUserAvatarParams) error {
	_, err := q.db.ExecContext(ctx, updateUserAvatar, arg.AvatarID, arg.ID)
	return err
}

const upsertAchievement = `-- name: UpsertAchievement :exec

INSERT OR IGNORE INTO achievements (key, name, description, icon)
VALUES (?, ?, ?, ?)
`

type UpsertAchievementParams struct {
	Key         string
	Name        string
	Description string
	Icon        string
}

// =============================================================================
// Achievements (Feature 8)
// =============================================================================
func (q *Queries) UpsertAchievement(ctx context.Context, arg UpsertAchievementParams) error {
	_, err := q.db.ExecContext(ctx, upsertAchievement,
		arg.Key,
		arg.Name,
		arg.Description,
		arg.Icon,
	)
	return err
}

const upsertAvatar = `-- name: UpsertAvatar :exec

INSERT OR IGNORE INTO avatars (key, name, image_path, category, achievement_key, sort_order)
VALUES (?, ?, ?, ?, ?, ?)
`

type UpsertAvatarParams struct {
	Key            string
	Name           string
	ImagePath      string
	Category       string
	AchievementKey sql.NullString
	SortOrder      int64
}

// =============================================================================
// Avatars
// =============================================================================
func (q *Queries) UpsertAvatar(ctx context.Context, arg UpsertAvatarParams) error {
	_, err := q.db.ExecContext(ctx, upsertAvatar,
		arg.Key,
		arg.Name,
		arg.ImagePath,
		arg.Category,
		arg.AchievementKey,
		arg.SortOrder,
	)
	return err
}

const upsertExchangeRate = `-- name: UpsertExchangeRate :exec

INSERT INTO exchange_rates (date, rate_aud_usd)
VALUES (?, ?)
ON CONFLICT(date) DO UPDATE SET rate_aud_usd = excluded.rate_aud_usd
`

type UpsertExchangeRateParams struct {
	Date       string
	RateAudUsd int64
}

// =============================================================================
// Exchange Rates
// =============================================================================
func (q *Queries) UpsertExchangeRate(ctx context.Context, arg UpsertExchangeRateParams) error {
	_, err := q.db.ExecContext(ctx, upsertExchangeRate, arg.Date, arg.RateAudUsd)
	return err
}

const upsertHolding = `-- name: UpsertHolding :exec

INSERT INTO holdings (participant_id, stock_id, quantity, avg_cost, current_value, updated_at)
VALUES (?, ?, ?, ?, 0, datetime('now'))
ON CONFLICT(participant_id, stock_id) DO UPDATE SET
    quantity = excluded.quantity,
    avg_cost = excluded.avg_cost,
    updated_at = datetime('now')
`

type UpsertHoldingParams struct {
	ParticipantID int64
	StockID       int64
	Quantity      int64
	AvgCost       int64
}

// =============================================================================
// Holdings
// =============================================================================
func (q *Queries) UpsertHolding(ctx context.Context, arg UpsertHoldingParams) error {
	_, err := q.db.ExecContext(ctx, upsertHolding,
		arg.ParticipantID,
		arg.StockID,
		arg.Quantity,
		arg.AvgCost,
	)
	return err
}

const upsertPrice = `-- name: UpsertPrice :exec

INSERT INTO stock_prices (stock_id, date, open, high, low, close, volume)
VALUES (?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(stock_id, date) DO UPDATE SET
    open = excluded.open, high = excluded.high, low = excluded.low,
    close = excluded.close, volume = excluded.volume
`

type UpsertPriceParams struct {
	StockID int64
	Date    string
	Open    int64
	High    int64
	Low     int64
	Close   int64
	Volume  int64
}

// =============================================================================
// Stock Prices
// =============================================================================
func (q *Queries) UpsertPrice(ctx context.Context, arg UpsertPriceParams) error {
	_, err := q.db.ExecContext(ctx, upsertPrice,
		arg.StockID,
		arg.Date,
		arg.Open,
		arg.High,
		arg.Low,
		arg.Close,
		arg.Volume,
	)
	return err
}

const upsertSnapshot = `-- name: UpsertSnapshot :exec

INSERT INTO portfolio_snapshots (participant_id, date, cash_balance, holdings_value, total_value)
VALUES (?, ?, ?, ?, ?)
ON CONFLICT(participant_id, date) DO UPDATE SET
    cash_balance = excluded.cash_balance,
    holdings_value = excluded.holdings_value,
    total_value = excluded.total_value
`

type UpsertSnapshotParams struct {
	ParticipantID int64
	Date          string
	CashBalance   int64
	HoldingsValue int64
	TotalValue    int64
}

// =============================================================================
// Portfolio Snapshots
// =============================================================================
func (q *Queries) UpsertSnapshot(ctx context.Context, arg UpsertSnapshotParams) error {
	_, err := q.db.ExecContext(ctx, upsertSnapshot,
		arg.ParticipantID,
		arg.Date,
		arg.CashBalance,
		arg.HoldingsValue,
		arg.TotalValue,
	)
	return err
}

const upsertUser = `-- name: UpsertUser :one

INSERT INTO users (google_id, email, name, picture_url, last_login)
VALUES (?, ?, ?, ?, datetime('now'))
ON CONFLICT(google_id) DO UPDATE SET
    email      = excluded.email,
    name       = excluded.name,
    picture_url = excluded.picture_url,
    last_login = datetime('now')
RETURNING id, google_id, email, name, picture_url, is_admin, avatar_id, created_at, last_login, deleted_at
`

type UpsertUserParams struct {
	GoogleID   string
	Email      string
	Name       string
	PictureUrl sql.NullString
}

// =============================================================================
// Users
// =============================================================================
func (q *Queries) UpsertUser(ctx context.Context, arg UpsertUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, upsertUser,
		arg.GoogleID,
		arg.Email,
		arg.Name,
		arg.PictureUrl,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.GoogleID,
		&i.Email,
		&i.Name,
		&i.PictureUrl,
		&i.IsAdmin,
		&i.AvatarID,
		&i.CreatedAt,
		&i.LastLogin,
		&i.DeletedAt,
	)
	return i, err
}
